export type BlogCategory = "Builds" | "Trail & Travel" | "Gear" | "Events" | "Culture";

/** A single content block in a post body. Supports the minimum structure a
 *  real article needs — section headings plus paragraphs — with **bold**
 *  inline emphasis parsed at render time (see renderInline in the post page). */
export type BlogBlock = { type: "heading"; text: string } | { type: "paragraph"; text: string };

export interface BlogPost {
  slug: string;
  title: string;
  /** Optional distinct <title>/OG title tuned for search — falls back to `title`. */
  seoTitle?: string;
  excerpt: string;
  /** Optional distinct <meta name="description"> copy — falls back to `excerpt`. */
  metaDescription?: string;
  category: BlogCategory;
  date: string; // ISO 8601
  image: { src: string; alt: string };
  /**
   * Full article body. Undefined until a real article is written for this
   * post — the listing only links to a post page once this exists, rather
   * than pointing "Read More" at nothing.
   */
  body?: BlogBlock[];
  /**
   * Manually curated — there's no analytics provider connected yet, so
   * "Editor's Picks" is editorial judgment rather than real view counts.
   * Revisit once real traffic data exists.
   */
  editorsPick?: boolean;
}

// Real excerpt copy from the original site. Full article bodies haven't
// been written yet for any of these — add `body` here (and the listing
// will start linking to /blog/{slug} automatically) whenever a real post
// is ready to publish.
export const posts: BlogPost[] = [
  {
    slug: "2027-corvette-grand-sport-does-it-need-z52",
    title: "Does the 2027 Corvette Grand Sport Really Need Z52 to Be a Track Car?",
    seoTitle: "2027 Corvette Grand Sport: Does It Need Z52?",
    excerpt:
      "Chevy says the 2027 Corvette Grand Sport blends street manners with track-ready engineering—but its Z52 packages are where the serious track hardware shows up. So should Z52 really be optional on a car called Grand Sport?",
    metaDescription:
      "Does the 2027 Corvette Grand Sport need Z52 for track use? We break down what Chevy confirms, what owners are debating, and what the badge should mean.",
    category: "Builds",
    date: "2026-08-20",
    image: { src: "/img/blog/corvette-grand-sport-z52.jpg", alt: "Does The 2027 Corvette Grand Sport Really Need Z52 To Be A Track Car? — a Grand Sport on a race track with a Base GS vs Z52 Packages callout" },
    body: [
      { type: "heading", text: "The Grand Sport Badge Comes With Expectations" },
      { type: "paragraph", text: "There are certain names you don't slap onto a car casually." },
      { type: "paragraph", text: "Z06." },
      { type: "paragraph", text: "GT3." },
      { type: "paragraph", text: "Shelby." },
      { type: "paragraph", text: "Grand Sport." },
      { type: "paragraph", text: "The **2027 Corvette Grand Sport** especially carries some baggage—in a good way. The original C2 Grand Sports were built around racing, and later versions of the car became the Corvette for people who wanted more chassis and tire than a base car without going all the way into the most expensive, most extreme version." },
      { type: "paragraph", text: "So when Chevrolet brought the name back for 2027, the pitch made sense." },
      { type: "paragraph", text: "The new Grand Sport starts at **$86,000** before destination, gets the wide-body C8 chassis, Magnetic Ride Control, 535 horsepower from Chevrolet's new naturally aspirated 6.7-liter LS6 V8, and is marketed by Chevrolet as a car blending everyday usability with track-focused engineering." },
      { type: "paragraph", text: "Sounds like a Grand Sport." },
      { type: "paragraph", text: "Then owners started reading the fine print." },

      { type: "heading", text: "The 2027 Corvette Grand Sport Z52 Question" },
      { type: "paragraph", text: "A CorvetteForum discussion has been digging into language attributed to the 2027 Corvette owner's manual regarding **track events and competitive driving**." },
      { type: "paragraph", text: "According to the manual language posted by multiple forum members, Grand Sport models equipped with **Z52 performance packages** are specifically listed among the Corvette configurations that can be used for track events and competitive driving." },
      { type: "paragraph", text: "That's where people started asking the obvious question:" },
      { type: "paragraph", text: "**What about the base Grand Sport?**" },
      { type: "paragraph", text: "We need to be precise here." },
      { type: "paragraph", text: "We were able to verify that Chevrolet's Corvette owner site links directly to the owner's manual and tells owners to use the track-preparation materials before track use. The current linked PDF wasn't retrievable through Chevrolet's site during our research, so we're not going to pretend we independently confirmed that exact sentence directly from the PDF." },
      { type: "paragraph", text: "But the same manual wording is reproduced across multiple CorvetteForum discussions." },
      { type: "paragraph", text: "So the owner concern is real." },
      { type: "paragraph", text: "What we **cannot** responsibly say is:" },
      { type: "paragraph", text: "“Chevy says the base Grand Sport is banned from the racetrack.”" },
      { type: "paragraph", text: "That's stronger than the evidence supports." },
      { type: "paragraph", text: "What we can say is that Chevrolet clearly distinguishes the base Grand Sport from the Z52-equipped cars when talking about the serious stuff." },
      { type: "paragraph", text: "And Chevrolet's own engineering descriptions make the distinction even clearer." },

      { type: "heading", text: "Chevy Built Three Different Grand Sports on Purpose" },
      { type: "paragraph", text: "This part isn't rumor." },
      { type: "paragraph", text: "Chevrolet says the base Grand Sport uses a **Touring Suspension**, standard Magnetic Ride Control, Michelin Pilot Sport All Season tires, and a lower-dust braking package." },
      { type: "paragraph", text: "Chevy's own engineers describe that version as the road-trip, canyon-road, everyday Grand Sport." },
      { type: "paragraph", text: "Then comes the **Z52 Sport Performance Package**." },
      { type: "paragraph", text: "That gets Michelin Pilot Sport 4S summer tires, a stiffer suspension tune, Performance Traction Management, and higher-performance iron brakes borrowed from the Z06 hardware family." },
      { type: "paragraph", text: "And this is important:" },
      { type: "paragraph", text: "Chevrolet specifically describes the Z52 Sport car as being intended for the enthusiast who plans to take the Grand Sport to the track." },
      { type: "paragraph", text: "Then there's another step." },
      { type: "paragraph", text: "The **Z52 Track Performance Package** gets carbon-ceramic brakes, Michelin Pilot Sport Cup 2 R tires, carbon-fiber aero, track-focused chassis tuning, and the quad center-exit exhaust." },
      { type: "paragraph", text: "That's the hammer." },
      { type: "paragraph", text: "But notice what Chevy did here." },
      { type: "paragraph", text: "It didn't build one Grand Sport and then offer a cosmetic option package." },
      { type: "paragraph", text: "It built three different levels of intent." },

      { type: "heading", text: "No, You Don't Need the Full Z52 Track Package" },
      { type: "paragraph", text: "This is where the headline can get screwed up fast." },
      { type: "paragraph", text: "If you're hearing:" },
      { type: "paragraph", text: "**“You have to buy carbon ceramics and Cup 2 Rs just to track the new Grand Sport,”**" },
      { type: "paragraph", text: "that's not what the available information shows." },
      { type: "paragraph", text: "There are **two Z52 packages**." },
      { type: "paragraph", text: "The Z52 Sport package is already the step Chevrolet positions toward track-day buyers. The full Z52 Track package is the more specialized configuration." },
      { type: "paragraph", text: "That's a major difference." },
      { type: "paragraph", text: "Chevrolet even entered a preproduction Grand Sport in the 2026 One Lap of America running the **Z52 Sport Performance Package**, not the full Track package." },
      { type: "paragraph", text: "That car finished **seventh overall and second in its class** after competing in road-course sessions, autocross, skidpad events, and long highway transits." },
      { type: "paragraph", text: "So let's kill one piece of potential clickbait right now:" },
      { type: "paragraph", text: "**You apparently do not need the most extreme Z52 package to have a serious track-capable Grand Sport.**" },
      { type: "paragraph", text: "The Z52 Sport package is clearly meant to do that job." },

      { type: "heading", text: "But Should a Grand Sport Need Any Package?" },
      { type: "paragraph", text: "Now we get to the actual argument." },
      { type: "paragraph", text: "And this is where we think Corvette owners have a point." },
      { type: "paragraph", text: "The base 2027 Grand Sport isn't some soft luxury coupe with a Corvette badge glued onto it." },
      { type: "paragraph", text: "It has 535 horsepower." },
      { type: "paragraph", text: "A wide body." },
      { type: "paragraph", text: "Forged wheels." },
      { type: "paragraph", text: "Magnetic Ride Control." },
      { type: "paragraph", text: "Serious brakes." },
      { type: "paragraph", text: "A mid-engine chassis." },
      { type: "paragraph", text: "Chevrolet itself describes the Grand Sport as being as capable on the track as it is on the street." },
      { type: "paragraph", text: "So when you tell a buyer:" },
      { type: "paragraph", text: "“Here's your Grand Sport.”" },
      { type: "paragraph", text: "Then add:" },
      { type: "paragraph", text: "“If you're actually planning track events, we'd steer you toward Z52.”" },
      { type: "paragraph", text: "You can understand why somebody scratches their head." },
      { type: "paragraph", text: "Especially when the car starts at eighty-six grand." },

      { type: "heading", text: "There's Also a Reason Chevy Did It" },
      { type: "paragraph", text: "Now for the other side." },
      { type: "paragraph", text: "Because Chevrolet isn't necessarily being unreasonable here." },
      { type: "paragraph", text: "The base Grand Sport comes on **all-season tires**." },
      { type: "paragraph", text: "That's the first clue." },
      { type: "paragraph", text: "Chevrolet wants that car to work in more conditions, ride comfortably, create less brake dust, and function as the Corvette you can actually drive everywhere." },
      { type: "paragraph", text: "That's probably the version a lot of owners should buy." },
      { type: "paragraph", text: "Realistically, plenty of Grand Sports will spend their lives doing highway miles, back roads, Cars & Coffee, dinner runs, and the occasional hard pull—not 20-minute track sessions cooking tires and brakes." },
      { type: "paragraph", text: "There's nothing wrong with that." },
      { type: "paragraph", text: "And if Chevy can offer those buyers better road manners while letting actual track-day people choose the proper brakes, tires, suspension calibration, and cooling prep they need, there is a legitimate engineering argument for doing it this way." },
      { type: "paragraph", text: "The issue isn't capability." },
      { type: "paragraph", text: "It's the **name**." },

      { type: "heading", text: "Grand Sport Used to Mean Something Pretty Specific" },
      { type: "paragraph", text: "Grand Sport has always lived in the middle." },
      { type: "paragraph", text: "Not just in price." },
      { type: "paragraph", text: "In purpose." },
      { type: "paragraph", text: "More serious than the base Corvette." },
      { type: "paragraph", text: "Less extreme than the top-tier track weapon." },
      { type: "paragraph", text: "That's exactly why people loved the C6 and C7 versions." },
      { type: "paragraph", text: "They were cars you could drive to work, drive across the state, then show up at a track day and beat on without feeling like you'd brought the wrong Corvette." },
      { type: "paragraph", text: "That identity is what Chevrolet is trying to preserve with the new one." },
      { type: "paragraph", text: "And frankly, the **Z52 Sport Grand Sport sounds like the true spiritual successor**." },
      { type: "paragraph", text: "You've still got the naturally aspirated V8." },
      { type: "paragraph", text: "You don't need carbon ceramics." },
      { type: "paragraph", text: "You don't need Cup 2 Rs." },
      { type: "paragraph", text: "You don't need maximum aero hanging off the car." },
      { type: "paragraph", text: "But you do get the serious brakes, summer rubber, firmer chassis calibration, and Performance Traction Management that make sense when you're running lap after lap." },
      { type: "paragraph", text: "That's the sweet spot." },
      { type: "paragraph", text: "Which is exactly what Grand Sport is supposed to be." },

      { type: "heading", text: "The Base Car Might Actually Need a Different Label" },
      { type: "paragraph", text: "Here's where we'll make the slightly unpopular argument." },
      { type: "paragraph", text: "The problem may not be that Chevrolet requires Z52 for the full Grand Sport track mission." },
      { type: "paragraph", text: "The problem might be that the **base configuration wears the same Grand Sport badge**." },
      { type: "paragraph", text: "Mechanically, the Touring version makes sense." },
      { type: "paragraph", text: "Marketing-wise?" },
      { type: "paragraph", text: "It muddies the story." },
      { type: "paragraph", text: "Chevy itself calls the Grand Sport an “all-around athlete,” while the Z06 is positioned as “track born, street ready.”" },
      { type: "paragraph", text: "Fair enough." },
      { type: "paragraph", text: "But if the base Grand Sport is deliberately optimized around all-season tires, quieter brakes, road trips, and street use, maybe buyers are justified in expecting the track-oriented hardware to be standard when the car wears one of Corvette's most historically competition-linked names." },
      { type: "paragraph", text: "That's not outrage." },
      { type: "paragraph", text: "It's just an identity question." },

      { type: "heading", text: "What We Know—and What We Don't" },
      { type: "paragraph", text: "**Confirmed:** The 2027 Corvette Grand Sport starts at $86,000 before destination and uses a 535-hp 6.7-liter naturally aspirated V8. The base car uses all-season tires and Touring-oriented chassis tuning. The Z52 Sport package adds summer tires, stronger iron brakes, firmer suspension tuning, and Performance Traction Management. The Z52 Track package goes further with carbon ceramics, Cup 2 R tires, carbon aero, and more focused chassis tuning. Chevrolet itself used a Z52 Sport Grand Sport—not the full Track package—to compete successfully in One Lap of America." },
      { type: "paragraph", text: "**Strongly supported, but worth reading carefully:** Multiple CorvetteForum owners have reproduced 2027 owner's-manual language identifying Z52-equipped Grand Sports for track events and competitive driving. We were not able to independently retrieve the currently linked Chevrolet PDF during this research, so we're not going to turn that wording into a warranty conclusion the source material doesn't explicitly establish." },
      { type: "paragraph", text: "**Not confirmed:** That taking a non-Z52 Grand Sport onto a racetrack automatically voids your warranty. That the base Grand Sport physically cannot handle a track day. That you need the full Z52 Track Performance Package just to run HPDE events." },
      { type: "paragraph", text: "Those are three very different claims." },
      { type: "paragraph", text: "Don't combine them." },

      { type: "heading", text: "So Does the Grand Sport Need Z52?" },
      { type: "paragraph", text: "For somebody who actually plans to track the car?" },
      { type: "paragraph", text: "**We'd order Z52 Sport.**" },
      { type: "paragraph", text: "Not because the base car suddenly becomes incapable the moment it crosses pit lane." },
      { type: "paragraph", text: "Because the package gives you the equipment we'd want anyway: better brakes, proper summer tires, firmer chassis tuning, and the electronics calibrated around that mission." },
      { type: "paragraph", text: "The full Z52 Track package?" },
      { type: "paragraph", text: "That's different." },
      { type: "paragraph", text: "Cup 2 Rs, carbon ceramics, and serious aero make a lot more sense for somebody chasing lap times than somebody planning two HPDE weekends a year." },
      { type: "paragraph", text: "Buy the car for what you're actually going to do with it." },
      { type: "paragraph", text: "That's advice that works whether we're talking Corvettes, Jeeps, UTVs, or anything else with tires." },
      { type: "paragraph", text: "But Chevrolet created this debate itself by putting the **Grand Sport** name on a Touring-spec version and then reserving the clearer track mission for Z52." },
      { type: "paragraph", text: "So here's the question we'd put to Corvette owners:" },
      { type: "paragraph", text: "**If you were ordering an $86,000-plus Grand Sport tomorrow, would you consider Z52 Sport mandatory because of what the Grand Sport badge should represent—or would you rather keep the all-season Touring setup and spend the money elsewhere?**" },
    ],
  },
  {
    slug: "cfmoto-vs-polaris-vs-can-am-what-are-you-paying-for",
    title: "CFMOTO vs Polaris vs Can-Am: What Are You Actually Paying For?",
    seoTitle: "CFMOTO vs Polaris vs Can-Am: What Are You Paying For?",
    excerpt:
      "CFMOTO keeps closing the gap while Polaris and Can-Am keep commanding premium prices. So what are you actually buying with the extra money—better hardware, better support, or just the badge?",
    metaDescription:
      "CFMOTO vs Polaris vs Can-Am: compare price, reliability, dealer support, resale and what UTV owners say you're really paying for.",
    category: "Gear",
    date: "2026-08-24",
    image: { src: "/img/blog/cfmoto-vs-polaris-vs-canam.jpg", alt: "CFMOTO vs Polaris vs Can-Am: What Are You Actually Paying For? — three UTVs lined up in the mud" },
    body: [
      { type: "paragraph", text: "Here's the question that keeps coming up:" },
      { type: "paragraph", text: "**If a CFMOTO gives you most of the same equipment for thousands less, what exactly are you paying extra for when you buy a Polaris Ranger or Can-Am Defender?**" },
      { type: "paragraph", text: "That's where the **CFMOTO vs Polaris vs Can-Am** argument gets interesting." },
      { type: "paragraph", text: "Because this isn't really a horsepower comparison anymore. CFMOTO has closed enough of the equipment and performance gap that buyers aren't automatically dismissing it as the cheap alternative." },
      { type: "paragraph", text: "Now they're asking whether the premium brands are actually better—or just more expensive." },
      { type: "paragraph", text: "And owners don't agree." },

      { type: "heading", text: "CFMOTO vs Polaris vs Can-Am Isn't Just About MSRP" },
      { type: "paragraph", text: "Walk around a newer CFMOTO UForce and the value proposition is pretty obvious." },
      { type: "paragraph", text: "You can get a lot of machine for the money. Features that might require packages, accessories or a higher trim elsewhere can be sitting there from day one." },
      { type: "paragraph", text: "That's exactly why the discussion has changed." },
      { type: "paragraph", text: "In a recent r/UTV ownership debate, buyers compared the UForce U10 directly against the Polaris Ranger and Can-Am Defender. One owner described a roughly **C$22,000 versus C$30,000** difference when comparing his CFMOTO purchase with a Ranger XP 1000." },
      { type: "paragraph", text: "Eight grand isn't pocket change." },
      { type: "paragraph", text: "That's a trailer. Tires. Winches. Communications gear. Camping equipment. Or a whole lot of fuel." },
      { type: "paragraph", text: "So if the cheaper machine does the same job, CFMOTO starts making a ton of sense." },
      { type: "paragraph", text: "But purchase price isn't the whole ownership experience." },

      { type: "heading", text: "You're Paying for the Dealer Network" },
      { type: "paragraph", text: "This came up repeatedly among actual owners." },
      { type: "paragraph", text: "Polaris and Can-Am have been in the North American SxS market long enough to build large dealer, service and parts networks. That matters when your machine stops moving." },
      { type: "paragraph", text: "An owner in the r/UTV discussion specifically chose Polaris because dealers, OEM parts and aftermarket parts were easier to find in his area. Other owners made similar points about being able to get repairs handled quickly instead of waiting on components or hunting for someone willing to work on the machine." },
      { type: "paragraph", text: "That doesn't mean CFMOTO has no support." },
      { type: "paragraph", text: "Its dealer network has grown significantly, and some owners report excellent warranty experiences—especially when they have a strong local dealer." },
      { type: "paragraph", text: "But that's the part people miss:" },
      { type: "paragraph", text: "**You're not just buying the UTV. You're buying the dealer standing behind it.**" },
      { type: "paragraph", text: "A great CFMOTO dealer five miles away might make the UForce the smarter purchase." },
      { type: "paragraph", text: "A weak dealer two hours away might completely change that equation." },

      { type: "heading", text: "Reliability Is Where the Arguments Get Loud" },
      { type: "paragraph", text: "Search long enough and you'll find somebody who has destroyed every brand." },
      { type: "paragraph", text: "There are Polaris owners with thousands of trouble-free miles." },
      { type: "paragraph", text: "There are Polaris owners who have replaced engines." },
      { type: "paragraph", text: "There are Can-Am owners who swear they'll never own anything else." },
      { type: "paragraph", text: "And there are CFMOTO owners beating their machines through work, snow and trails with no major problems." },
      { type: "paragraph", text: "One CFMOTO ATV owner recently described running a 2022 machine hard for utility work—plowing, pulling trailers and hauling wood—with no reported issues. Another UTV owner said his CFMOTO had been in the shop six or seven times for problems involving sensors, the fuel system, stator, front differential and other components." },
      { type: "paragraph", text: "Those experiences are real." },
      { type: "paragraph", text: "They're also individual experiences." },
      { type: "paragraph", text: "That's important." },
      { type: "paragraph", text: "One blown engine doesn't prove Polaris is unreliable. One flawless CFMOTO doesn't prove the brand has completely erased the long-term durability question." },
      { type: "paragraph", text: "What matters is the pattern over thousands of machines and years of ownership." },
      { type: "paragraph", text: "And that's where Polaris and Can-Am still have an advantage: **there's simply more long-term ownership history to examine.**" },

      { type: "heading", text: "What About Resale?" },
      { type: "paragraph", text: "This is where the cheaper purchase price can come back into the conversation later." },
      { type: "paragraph", text: "Established brands generally benefit from stronger name recognition in the used market. Buyers know what a Ranger is. They know the Defender. There are years of used machines, parts, accessories and community knowledge behind them." },
      { type: "paragraph", text: "CFMOTO is improving here, but owners still regularly mention resale as part of the premium-brand advantage. Even dealers comparing the brands tend to frame CFMOTO around upfront value while Polaris and Can-Am benefit from stronger long-term market recognition and parts ecosystems." },
      { type: "paragraph", text: "But resale only matters if you're selling." },
      { type: "paragraph", text: "If you plan on buying a machine, maintaining it and running it into the ground for ten years?" },
      { type: "paragraph", text: "That changes the math." },
      { type: "paragraph", text: "Paying $5,000 or $8,000 less upfront can be pretty powerful." },

      { type: "heading", text: "The Aftermarket Is Part of the Price Too" },
      { type: "paragraph", text: "Jeep people already understand this." },
      { type: "paragraph", text: "You don't just buy the vehicle." },
      { type: "paragraph", text: "You buy into an ecosystem." },
      { type: "paragraph", text: "Polaris has an enormous accessory and aftermarket catalog. Can-Am isn't exactly hurting either." },
      { type: "paragraph", text: "Doors. Windshields. Suspension. Clutches. Wheels. Storage. Cab systems. Plows. Audio. Lighting. Replacement parts." },
      { type: "paragraph", text: "CFMOTO's aftermarket continues to grow, but the older brands still have the advantage when you want three different versions of the same weird bracket delivered by Friday." },
      { type: "paragraph", text: "That convenience has value." },
      { type: "paragraph", text: "How much value depends entirely on how you use your machine." },

      { type: "heading", text: "So Is CFMOTO the Better Deal?" },
      { type: "paragraph", text: "Sometimes." },
      { type: "paragraph", text: "That's the answer nobody likes because it doesn't start a brand war." },
      { type: "paragraph", text: "If you're looking at a **CFMOTO UForce**, the machine has the features you want, you've got a good local dealer and the price difference is substantial?" },
      { type: "paragraph", text: "We wouldn't dismiss it because somebody on the internet still thinks CFMOTO is the same company it was ten years ago." },
      { type: "paragraph", text: "But if you're running a machine every week, depending on it for work, modifying it heavily or keeping it somewhere downtime becomes a real problem?" },
      { type: "paragraph", text: "That Polaris or Can-Am premium starts buying something tangible." },
      { type: "paragraph", text: "**Parts. Dealers. Aftermarket support. Ownership history. Resale.**" },
      { type: "paragraph", text: "Not just a logo." },

      { type: "heading", text: "Buy the Machine—and the Support Behind It" },
      { type: "paragraph", text: "The wrong way to compare these machines is:" },
      { type: "paragraph", text: "**“Which one has the biggest number on the spec sheet?”**" },
      { type: "paragraph", text: "The better question is:" },
      { type: "paragraph", text: "**“What happens three years after I buy it?”**" },
      { type: "paragraph", text: "Who fixes it?" },
      { type: "paragraph", text: "How fast can you get the part?" },
      { type: "paragraph", text: "Can you modify it the way you want?" },
      { type: "paragraph", text: "What's it worth when you sell it?" },
      { type: "paragraph", text: "And how much money did you save—or spend—getting there?" },
      { type: "paragraph", text: "CFMOTO is forcing Polaris and Can-Am to answer those questions because the price gap is getting harder to ignore." },
      { type: "paragraph", text: "That's good for buyers." },
      { type: "paragraph", text: "So here's ours:" },
      { type: "paragraph", text: "**Would you rather save $5,000–$8,000 upfront on a well-equipped CFMOTO, or spend more for the dealer network, aftermarket and resale behind a Polaris or Can-Am?**" },
      { type: "paragraph", text: "If you've actually owned one of these machines, we want to hear the experience—not the brand loyalty." },
      { type: "paragraph", text: "Tell us what broke, what didn't, what the dealer did about it, and whether you'd buy the same machine again." },
      { type: "paragraph", text: "That's the information that actually helps somebody spend their money." },
    ],
  },
  {
    slug: "jeep-gladiator-392-stop-calling-rumors-facts",
    title: "Jeep Gladiator 392: Stop Calling Rumors Facts",
    excerpt:
      "Everyone keeps saying the Jeep Gladiator 392 is confirmed—but the details aren't nearly that simple. We separate what Jeep has actually said from the rumors, assumptions, and enthusiast wish lists.",
    metaDescription:
      "The Jeep Gladiator 392 hype is everywhere. Here's what Jeep has actually confirmed, what remains speculation, and what owners should watch next.",
    category: "Builds",
    date: "2026-09-03",
    image: { src: "/img/blog/gladiator-392-rumors.jpg", alt: "Gladiator 392 — Stop Calling Rumors Facts: a lifted Jeep Gladiator Rubicon on 37s kicking up dust" },
    body: [
      { type: "paragraph", text: "The **Jeep Gladiator 392** is confirmed." },
      { type: "paragraph", text: "Except maybe it isn't." },
      { type: "paragraph", text: "That's the problem." },
      { type: "paragraph", text: "For more than a year, Jeep forums, enthusiast pages, YouTube channels, and social feeds have been repeating some version of the same headline: **“392 Gladiator confirmed.”**" },
      { type: "paragraph", text: "And look—we want one too." },
      { type: "paragraph", text: "A factory V8 Gladiator makes almost too much sense. You get the removable doors, solid axles, truck bed, trail capability, and then you drop a Hemi into the middle of it." },
      { type: "paragraph", text: "That's basically Asphalt and Dirt in vehicle form." },
      { type: "paragraph", text: "But wanting something to be true and having Jeep officially put it on an order sheet are two different things." },
      { type: "paragraph", text: "Right now, enthusiasts need to stop treating those two things like they're the same." },

      { type: "heading", text: "What Jeep Has Actually Said About a V8 Gladiator" },
      { type: "paragraph", text: "The hype really took off after Jeep CEO Bob Broderdorf made comments in 2025 about the future of Hemi power within the Jeep lineup." },
      { type: "paragraph", text: "He made it clear that the 6.4-liter Hemi still had a home at Jeep and specifically reassured Wrangler and Gladiator fans that Hemi wasn't disappearing from the conversation." },
      { type: "paragraph", text: "That was enough to light the fuse." },
      { type: "paragraph", text: "The Jeep Gladiator Forum thread built around those comments has now grown to roughly **140 pages, more than 2,000 posts, and over 120 watchers**. Owners are still dissecting every interview, order guide, production rumor, and Stellantis announcement looking for confirmation." },
      { type: "paragraph", text: "That's not a small amount of interest." },
      { type: "paragraph", text: "But here's the key distinction:" },
      { type: "paragraph", text: "**Jeep signaling that a Hemi-powered Gladiator is coming is not the same as Jeep announcing a Gladiator Rubicon 392 with confirmed specifications, pricing, and production dates.**" },
      { type: "paragraph", text: "Those details matter." },

      { type: "heading", text: "The Jeep Gladiator 392 Has Not Been Fully Defined" },
      { type: "paragraph", text: "When most people hear “Gladiator 392,” they picture something very specific." },
      { type: "paragraph", text: "A 6.4-liter Hemi." },
      { type: "paragraph", text: "Roughly Wrangler 392 levels of power." },
      { type: "paragraph", text: "Probably some version of a Rubicon or Mojave." },
      { type: "paragraph", text: "Heavy-duty axles." },
      { type: "paragraph", text: "Big brakes." },
      { type: "paragraph", text: "Aggressive suspension." },
      { type: "paragraph", text: "And a price tag that hurts just enough to make us complain about it before buying one anyway." },
      { type: "paragraph", text: "The problem is that Jeep has not publicly locked all of that down." },
      { type: "paragraph", text: "Even inside the major Gladiator forum discussion, owners have questioned whether the eventual V8 could actually be a **5.7-liter Hemi instead of the 6.4-liter 392**. Others have pointed out that recent Stellantis presentations and executive comments haven't always used “392” when discussing future Gladiator powertrains." },
      { type: "paragraph", text: "That doesn't mean the 392 isn't coming." },
      { type: "paragraph", text: "It means we don't know enough yet to present it as finished fact." },

      { type: "heading", text: "The 2027 Jeep Gladiator Order Information Matters" },
      { type: "paragraph", text: "This is where things get interesting." },
      { type: "paragraph", text: "As of late August 2026, enthusiasts are already discussing updated **2027 Jeep Gladiator order-guide information**." },
      { type: "paragraph", text: "There are new equipment combinations, trim changes, colors, and ongoing speculation about future models." },
      { type: "paragraph", text: "What isn't sitting there as a normal, clearly orderable production vehicle?" },
      { type: "paragraph", text: "A Gladiator 392." },
      { type: "paragraph", text: "The 2027 order-guide discussions are active right now, and owners are already debating missing trims and packages." },
      { type: "paragraph", text: "At the same time, Jeep's own current Gladiator page is teasing additional upcoming “Classified” models as part of its 2027 lineup campaign. Jeep isn't identifying those vehicles yet." },
      { type: "paragraph", text: "Could one be the V8?" },
      { type: "paragraph", text: "Absolutely." },
      { type: "paragraph", text: "Can we call that confirmation?" },
      { type: "paragraph", text: "No." },
      { type: "paragraph", text: "That's exactly how rumors turn into “facts.”" },
      { type: "paragraph", text: "Someone sees a blank space." },
      { type: "paragraph", text: "Someone connects it to a CEO comment." },
      { type: "paragraph", text: "Another account posts “392 CONFIRMED.”" },
      { type: "paragraph", text: "Ten reposts later, everybody thinks Jeep issued a press release." },

      { type: "heading", text: "Why Jeep Owners Want the V8 So Badly" },
      { type: "paragraph", text: "The obsession isn't hard to understand." },
      { type: "paragraph", text: "The Gladiator has always had the chassis and personality for more power." },
      { type: "paragraph", text: "The 3.6-liter Pentastar gets the job done, but once you start adding 35s, 37s, armor, bumpers, recovery equipment, camping gear, and everything else we bolt onto these trucks, 285 horsepower starts feeling a lot less exciting." },
      { type: "paragraph", text: "And the Hemi solves more than a horsepower problem." },
      { type: "paragraph", text: "It's the sound." },
      { type: "paragraph", text: "The throttle response." },
      { type: "paragraph", text: "The simplicity and familiarity enthusiasts associate with a naturally aspirated V8." },
      { type: "paragraph", text: "The fact that a ridiculous engine in an equally ridiculous removable-roof pickup just feels right." },
      { type: "paragraph", text: "Forum owners are even debating whether they'd rather have a traditional Hemi than a more powerful Hurricane inline-six because horsepower isn't the only part of the ownership equation." },
      { type: "paragraph", text: "That's a real conversation." },

      { type: "heading", text: "Then There's the Price" },
      { type: "paragraph", text: "This might decide whether the Hemi Gladiator becomes a hero or another vehicle everybody loves but few people buy." },
      { type: "paragraph", text: "The Wrangler 392 proved Jeep enthusiasts will spend serious money for V8 power." },
      { type: "paragraph", text: "But the Gladiator market is different." },
      { type: "paragraph", text: "It's already competing against midsize pickups that can tow, haul, and daily-drive extremely well for substantially less money." },
      { type: "paragraph", text: "The forum discussion keeps circling back to the same question:" },
      { type: "paragraph", text: "**How much extra should a V8 really cost?**" },
      { type: "paragraph", text: "Some owners argue that adding tens of thousands of dollars for the engine turns the whole thing into a luxury toy. Others say a factory Hemi, warranty, upgraded drivetrain, and resale value justify the premium." },
      { type: "paragraph", text: "That's probably where the real battle will happen." },
      { type: "paragraph", text: "Not whether people want it." },
      { type: "paragraph", text: "Whether enough people want it **at Jeep's price.**" },

      { type: "heading", text: "What We Know, What We Think, and What We Don't Know" },
      { type: "paragraph", text: "Here's where Asphalt and Dirt stands." },
      { type: "paragraph", text: "**We know:** Jeep leadership has publicly made it clear that Hemi power remains part of Jeep's future and has specifically included Gladiator fans in that conversation." },
      { type: "paragraph", text: "**We have strong reason to believe:** A factory V8 Gladiator is a serious possibility and may be part of upcoming product announcements." },
      { type: "paragraph", text: "**We do not know:**" },
      { type: "paragraph", text: "The final engine displacement." },
      { type: "paragraph", text: "The final trim." },
      { type: "paragraph", text: "Horsepower." },
      { type: "paragraph", text: "Torque." },
      { type: "paragraph", text: "Axle package." },
      { type: "paragraph", text: "Suspension." },
      { type: "paragraph", text: "Towing capacity." },
      { type: "paragraph", text: "Price." },
      { type: "paragraph", text: "Actual order date." },
      { type: "paragraph", text: "Actual production date." },
      { type: "paragraph", text: "Until Jeep publishes those details, they're not facts." },
      { type: "paragraph", text: "They're educated guesses." },

      { type: "heading", text: "Stop Killing the Story by Pretending We Already Know It" },
      { type: "paragraph", text: "Here's the funny part." },
      { type: "paragraph", text: "The actual story is better than the rumor." },
      { type: "paragraph", text: "Jeep has a product enthusiasts have begged for almost since the Gladiator launched." },
      { type: "paragraph", text: "The Hemi is alive again." },
      { type: "paragraph", text: "Jeep is teasing future Gladiator models." },
      { type: "paragraph", text: "The community is watching every move." },
      { type: "paragraph", text: "And we genuinely don't know exactly what Jeep is about to do." },
      { type: "paragraph", text: "That's interesting." },
      { type: "paragraph", text: "We don't need to manufacture certainty where it doesn't exist." },
      { type: "paragraph", text: "If Jeep announces a 470-horsepower Gladiator Rubicon 392 tomorrow, we'll be right there talking about it." },
      { type: "paragraph", text: "But until the build sheet exists, let's call it what it is:" },
      { type: "paragraph", text: "**A V8 Gladiator looks increasingly likely.**" },
      { type: "paragraph", text: "A fully confirmed **Jeep Gladiator 392** with known specs, pricing, and production?" },
      { type: "paragraph", text: "Not yet." },
      { type: "paragraph", text: "And now the important question:" },
      { type: "paragraph", text: "**If Jeep gives us the V8 Gladiator, what would you actually pay for it?**" },
      { type: "paragraph", text: "Would you spend Wrangler 392 money?" },
      { type: "paragraph", text: "Or does Jeep need to keep this thing under control for it to make sense?" },
      { type: "paragraph", text: "Let us know." },
      { type: "paragraph", text: "Because if this truck finally drops, the price might start a bigger fight than the engine ever did." },
    ],
  },
  {
    slug: "california-tire-rules-what-enthusiasts-need-to-know",
    title: "California Tire Rules: What Enthusiasts Actually Need to Know",
    seoTitle: "California Tire Rules: What Enthusiasts Need to Know",
    excerpt:
      "California didn't ban your 37s—but its new tire rules could still matter to Jeep, off-road and performance owners. Here's what the regulation actually says, what it doesn't, and what enthusiasts should be watching.",
    metaDescription:
      "California tire rules are changing. Here's what the new standards actually mean for off-road tires, performance tires, 35s, 37s and more.",
    category: "Gear",
    date: "2026-08-31",
    image: { src: "/img/blog/california-tire-rules.jpg", alt: "California Tire Rules: What It Really Means — a muddy Jeep Rubicon on 37s next to a crossed-out tire graphic" },
    body: [
      { type: "paragraph", text: "No, California did not just ban your 37s." },
      { type: "paragraph", text: "It didn't outlaw lifted Jeeps. It didn't require everybody to run factory-size tires. And nobody from Sacramento is coming to measure the rubber under your Wrangler." },
      { type: "paragraph", text: "But the **California tire rules** that were approved in August are real, and if you're into Jeeps, off-roading, street builds or track cars, they're worth paying attention to." },
      { type: "paragraph", text: "Because underneath some of the social-media outrage is a legitimate question:" },
      { type: "paragraph", text: "**What happens when tire efficiency regulations meet enthusiast vehicles?**" },
      { type: "paragraph", text: "That part is worth talking about." },

      { type: "heading", text: "What California Actually Approved" },
      { type: "paragraph", text: "On August 17, 2026, the California Energy Commission approved its Replacement Tire Efficiency Program, the first state standards of their kind in the country." },
      { type: "paragraph", text: "The rules apply to replacement tires sold for passenger vehicles and light-duty trucks in California. Phase one begins in **2029**, with stricter requirements taking effect in **2033**." },
      { type: "paragraph", text: "The basic idea is straightforward: replacement tires shouldn't dramatically reduce the efficiency a vehicle had when it left the factory." },
      { type: "paragraph", text: "Tires create rolling resistance. More rolling resistance means the engine—or electric motor—needs more energy to keep the vehicle moving. California wants replacement tires to meet minimum efficiency standards while maintaining requirements for wet grip and other performance characteristics." },
      { type: "paragraph", text: "That's the rule." },
      { type: "paragraph", text: "There is nothing in the regulation saying your Jeep has to stay on the tire size printed on the door jamb." },

      { type: "heading", text: "California Tire Rules Aren't Tire-Size Rules" },
      { type: "paragraph", text: "This is where the internet started getting sideways." },
      { type: "paragraph", text: "Some enthusiast discussions quickly turned the regulation into some version of:" },
      { type: "paragraph", text: "**“California is banning oversized tires.”**" },
      { type: "paragraph", text: "That's not what the adopted program says." },
      { type: "paragraph", text: "The rule establishes efficiency requirements for tires being sold. It does **not** establish a maximum 33-, 35-, 37- or 40-inch tire size for your vehicle." },
      { type: "paragraph", text: "There are also exemptions built into the program, including limited-production tires, high-load-index tires and tires that cannot sustain speeds above 50 mph. The California Energy Commission also says accommodations were made for certain specialty categories, including competition tires and some large off-road tires." },
      { type: "paragraph", text: "So can everyone with a Jeep on 37s stop caring?" },
      { type: "paragraph", text: "Not exactly." },

      { type: "heading", text: "The Real Question for Off-Road Tires" },
      { type: "paragraph", text: "The better question isn't:" },
      { type: "paragraph", text: "**“Are they banning 37s?”**" },
      { type: "paragraph", text: "It's:" },
      { type: "paragraph", text: "**“Which 37s will manufacturers still be willing to sell in California once these standards take effect?”**" },
      { type: "paragraph", text: "That's a much more complicated conversation." },
      { type: "paragraph", text: "A 37-inch all-terrain designed for highway use is a very different product from a competition-specific tire or a massive low-speed rock-crawling tire." },
      { type: "paragraph", text: "And that's where enthusiast concerns become legitimate." },
      { type: "paragraph", text: "The CEC's own public rulemaking docket continued receiving comments after the regulation was adopted asking for additional review of specialty-performance tires and raising concerns about off-road tires, consumer choice and cost." },
      { type: "paragraph", text: "Those comments are opinions and concerns—not proof that specific tires will disappear." },
      { type: "paragraph", text: "That distinction matters." },
      { type: "paragraph", text: "Right now, anyone telling you that a specific BFGoodrich, Nitto, Falken, Toyo or Mickey Thompson tire is definitely going to be banned needs to show the actual classification and compliance data for that tire." },
      { type: "paragraph", text: "Otherwise, they're guessing." },

      { type: "heading", text: "Performance Car Owners Should Be Watching Too" },
      { type: "paragraph", text: "This isn't just a Jeep story." },
      { type: "paragraph", text: "Street cars, autocross cars and track builds often live on specialty rubber where outright grip matters far more than fuel economy." },
      { type: "paragraph", text: "Ultra-high-performance tires, 200-treadwear tires, drag-oriented tires and competition tires are all designed around different priorities." },
      { type: "paragraph", text: "California says its testing found the efficiency standards can be met without sacrificing safety, tire lifespan or other important characteristics, and the regulations include separate treatment for several specialty categories." },
      { type: "paragraph", text: "Manufacturers—including major tire companies—were involved during years of stakeholder discussions." },
      { type: "paragraph", text: "Still, enthusiasts have a fair reason to watch what happens next." },
      { type: "paragraph", text: "Because what works technically isn't always the same thing as what manufacturers decide makes financial sense to keep producing." },

      { type: "heading", text: "Could This Spread Beyond California?" },
      { type: "paragraph", text: "This might be the bigger story." },
      { type: "paragraph", text: "California is often large enough as a market that manufacturers don't simply build completely different product lines for the state." },
      { type: "paragraph", text: "If tire manufacturers redesign products to meet California's requirements, some of those changes could eventually affect what gets sold elsewhere." },
      { type: "paragraph", text: "That's not guaranteed." },
      { type: "paragraph", text: "But it's one reason an off-road owner in New Jersey, Pennsylvania or anywhere else shouldn't dismiss this as somebody else's problem." },
      { type: "paragraph", text: "California may be where the regulation started." },
      { type: "paragraph", text: "The tire industry isn't confined by state lines." },

      { type: "heading", text: "There's Another Side to This" },
      { type: "paragraph", text: "It's also worth acknowledging why these rules exist." },
      { type: "paragraph", text: "According to the California Energy Commission, more efficient replacement tires could eventually save California motorists nearly **$1 billion annually** in gasoline and electricity costs." },
      { type: "paragraph", text: "The agency estimates Phase 1 could add around **$6 to the cost of a set of four tires** while producing roughly $85 in energy savings over their life. Phase 2 estimates put the added tire cost around $26 per set against $179 in projected savings." },
      { type: "paragraph", text: "You can agree with the policy, hate the policy or question those projections." },
      { type: "paragraph", text: "But that's the actual argument." },
      { type: "paragraph", text: "Not government-approved 32s versus illegal 37s." },

      { type: "heading", text: "What Asphalt and Dirt Is Watching" },
      { type: "paragraph", text: "For us, three things matter going forward." },
      { type: "paragraph", text: "**Availability.** Do popular enthusiast tires continue being sold without major changes?" },
      { type: "paragraph", text: "**Performance.** Can manufacturers reduce rolling resistance without sacrificing the traction, durability and sidewall strength off-road owners actually need?" },
      { type: "paragraph", text: "**Cost.** Will specialty tires become noticeably more expensive because manufacturers have to redesign, test or certify additional products?" },
      { type: "paragraph", text: "Those answers probably won't come from Facebook memes." },
      { type: "paragraph", text: "They'll come from manufacturers, published compliance information and what eventually shows up—or disappears—from tire racks." },

      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "Your 37s aren't suddenly illegal." },
      { type: "paragraph", text: "Your lifted Jeep isn't being forced back onto stock rubber." },
      { type: "paragraph", text: "And California hasn't outlawed performance tires." },
      { type: "paragraph", text: "But dismissing the entire thing because the loudest claims are wrong would be a mistake too." },
      { type: "paragraph", text: "The **California tire rules** represent a real change in how replacement tires will be regulated, and enthusiast applications sit right where efficiency standards, performance requirements and consumer choice collide." },
      { type: "paragraph", text: "That's a conversation worth having without turning it into panic." },
      { type: "paragraph", text: "So here's the question:" },
      { type: "paragraph", text: "**If a new tire delivered the same traction, durability and off-road performance as the tire you're running now—but used less fuel—would you care?**" },
      { type: "paragraph", text: "Or is tire efficiency something that should stay completely out of enthusiast vehicle culture?" },
      { type: "paragraph", text: "Drop your take. This one is going to get interesting." },
    ],
  },
  {
    slug: "what-makes-a-daily-driver-trail-ready",
    title: "What Makes A Daily Driver Trail Ready",
    excerpt: "Highlights, laughs, and lessons from an epic weekend on red clay and good vibes.",
    category: "Builds",
    date: "2025-05-30",
    image: { src: "/img/builds/rock-rhino.jpg", alt: "Jeep built as a daily driver on a trail" },
  },
  {
    slug: "the-gear-we-actually-use",
    title: "The Gear We Actually Use",
    excerpt: "Our favorite upgrades and gear that actually hold up when the trail gets tough.",
    category: "Gear",
    date: "2025-05-27",
    image: { src: "/img/blog/gear-flatlay.jpg", alt: "Flatlay of off-road recovery gear" },
  },
  {
    slug: "red-clay-run-community-ride-recap",
    title: "Red Clay Run: Community Ride Recap",
    excerpt: "Highlights, laughs, and lessons from an epic weekend on red clay and good vibes.",
    category: "Events",
    date: "2025-05-24",
    image: { src: "/img/blog/trail-convoy.jpg", alt: "Aerial view of a Jeep convoy on a trail" },
  },
  {
    slug: "overland-setup-essentials",
    title: "Overland Setup Essentials",
    excerpt: "The gear, mods, and systems that make long trips smoother.",
    category: "Trail & Travel",
    date: "2025-05-11",
    image: { src: "/img/podcast/ep-convoy.jpg", alt: "Overland-equipped Jeep convoy on a forest road" },
    editorsPick: true,
  },
  {
    slug: "tires-101-choosing-traction",
    title: "Tires 101: Choosing Traction",
    excerpt: "Our guide to picking the right rubber for any terrain.",
    category: "Gear",
    date: "2025-05-07",
    image: { src: "/img/community/trail-cleanup.jpg", alt: "Close-up of an off-road tire and wheel" },
    editorsPick: true,
  },
  {
    slug: "why-community-rides-matter",
    title: "Why Community Rides Matter",
    excerpt: "It's more than the trails—it's the people who show up.",
    category: "Culture",
    date: "2025-05-03",
    image: { src: "/img/blog/campfire-culture.jpg", alt: "Friends gathered around a campfire" },
    editorsPick: true,
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug && p.body);
}

export function getPublishedPosts(): BlogPost[] {
  return posts.filter((p) => p.body);
}

/** Every post, newest first — the full archive, not just a curated slice. */
export function getAllPostsSorted(): BlogPost[] {
  return [...posts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getEditorsPicks(): BlogPost[] {
  return posts.filter((p) => p.editorsPick);
}
