export type BlogCategory = "Builds" | "Trail & Travel" | "Gear" | "Events" | "Culture";

/** A single content block in a post body. Supports the minimum structure a
 *  real article needs — section headings plus paragraphs — with **bold**
 *  inline emphasis parsed at render time (see renderInline in the post page). */
export type BlogBlock = { type: "heading"; text: string } | { type: "paragraph"; text: string };

export interface BlogPost {
  slug: string;
  title: string;
  /** Optional distinct <title>/OG title tuned for search — falls back to `title`. */
  seoTitle?: string;
  excerpt: string;
  /** Optional distinct <meta name="description"> copy — falls back to `excerpt`. */
  metaDescription?: string;
  category: BlogCategory;
  date: string; // ISO 8601
  image: { src: string; alt: string };
  /**
   * Full article body. Undefined until a real article is written for this
   * post — the listing only links to a post page once this exists, rather
   * than pointing "Read More" at nothing.
   */
  body?: BlogBlock[];
  /**
   * Manually curated — there's no analytics provider connected yet, so
   * "Editor's Picks" is editorial judgment rather than real view counts.
   * Revisit once real traffic data exists.
   */
  editorsPick?: boolean;
}

// Real excerpt copy from the original site. Full article bodies haven't
// been written yet for any of these — add `body` here (and the listing
// will start linking to /blog/{slug} automatically) whenever a real post
// is ready to publish.
export const posts: BlogPost[] = [
  {
    slug: "dodge-charger-hurricane-does-muscle-need-a-v8",
    title: "The New Charger Has the Power. Does It Have the Soul?",
    seoTitle: "Dodge Charger Hurricane: Does Muscle Need a V8?",
    excerpt:
      "The Dodge Charger Hurricane has plenty of power. The harder question is whether 550 turbocharged horsepower can replace the sound, character and irrational appeal that made people want a HEMI Charger in the first place.",
    metaDescription:
      "The Dodge Charger Hurricane makes serious power without a V8. But does speed alone make it a muscle car? We dig into the debate.",
    category: "Culture",
    date: "2026-09-06",
    image: { src: "/img/blog/dodge-charger-hurricane-v8-debate.jpg", alt: "The New Charger Has The Power. Does It Have The Soul? — a Dodge Charger Hurricane SIXPACK Scat Pack drifting past a classic HEMI Charger, with Serious Performance / Missing The V8 Sound? / Real Muscle Or Just Numbers? callouts" },
    body: [
      { type: "heading", text: "The Argument Isn't Really About Horsepower" },
      { type: "paragraph", text: "Let's get something out of the way immediately." },
      { type: "paragraph", text: "The new Dodge Charger Hurricane does not have a power problem." },
      { type: "paragraph", text: "The gas-powered 2026 Charger Scat Pack uses Dodge's 3.0-liter twin-turbo SIXPACK High Output straight-six making 550 horsepower and 531 lb-ft of torque. Dodge says it will hit 60 mph in 3.9 seconds and run the quarter-mile in 12.2 seconds. The R/T gets a 420-horsepower version producing 468 lb-ft. Both come standard with all-wheel drive, with the Scat Pack able to send power exclusively to the rear wheels." },
      { type: "paragraph", text: "Those aren't apology numbers." },
      { type: "paragraph", text: "They're not “pretty good for a six-cylinder” numbers, either." },
      { type: "paragraph", text: "The 420-horsepower R/T actually makes more horsepower and torque than the previous 5.7-liter HEMI-powered Charger R/T it replaces, according to Dodge." },
      { type: "paragraph", text: "So why are people still arguing about this car?" },
      { type: "paragraph", text: "Because muscle cars were never just math." },

      { type: "heading", text: "Dodge Charger Hurricane: Faster Doesn't Automatically Mean Better" },
      { type: "paragraph", text: "This is where spec-sheet arguments start falling apart." },
      { type: "paragraph", text: "There is a perfectly reasonable case for the SIXPACK Charger. Twin turbos. Big torque. Standard AWD. Serious tuning potential. Two doors or four. A modern chassis. And enough power in Scat Pack form to embarrass a lot of cars carrying much more exotic badges." },
      { type: "paragraph", text: "Car and Driver's testing of the 550-horsepower Charger Scat Pack recorded a 3.7-second run to 60 mph, while its reviewers also came away impressed by how much more capable the new platform feels in corners than previous Chargers." },
      { type: "paragraph", text: "None of that makes the opposing argument disappear." },
      { type: "paragraph", text: "Because ask somebody why they bought a 5.7, 6.4 or Hellcat Charger and “optimal engineering efficiency” probably isn't going to be the first sentence out of their mouth." },
      { type: "paragraph", text: "The sound mattered." },
      { type: "paragraph", text: "The idle mattered." },
      { type: "paragraph", text: "The way the thing fired up mattered." },
      { type: "paragraph", text: "Rolling into the throttle and hearing a naturally aspirated V8—or a supercharged one trying to tear the rear tires apart—was part of the purchase." },
      { type: "paragraph", text: "You didn't need a timing slip to understand the appeal." },

      { type: "heading", text: "Muscle Cars Have Always Sold Some Irrationality" },
      { type: "paragraph", text: "Enthusiasts are wonderfully inconsistent people." },
      { type: "paragraph", text: "We'll spend thousands of dollars making something louder, lower, higher, wider or objectively less practical because the end result makes us turn around and look at it after parking." },
      { type: "paragraph", text: "Street guys understand it." },
      { type: "paragraph", text: "So do Jeep owners running 37s they absolutely did not need to drive to work Monday morning." },
      { type: "paragraph", text: "So do SxS owners, dirt-bike riders and anybody who has ever justified another suspension upgrade with the phrase, “while we're already in there.”" },
      { type: "paragraph", text: "Automotive enthusiasm has never required everything to make rational sense." },
      { type: "paragraph", text: "That's why saying, “But the new Charger is faster,” doesn't settle anything." },
      { type: "paragraph", text: "A modern turbo six can outperform an older V8 and still provide a completely different experience." },
      { type: "paragraph", text: "Both things can be true." },

      { type: "heading", text: "The SIXPACK Isn't Some Random Economy-Car Engine" },
      { type: "paragraph", text: "There's also a lazy version of the criticism that deserves to die." },
      { type: "paragraph", text: "The Hurricane-powered Charger isn't Dodge dropping some base commuter engine between the fenders and asking everyone to pretend." },
      { type: "paragraph", text: "Dodge's High Output version runs two 54mm Garrett turbochargers and as much as 30 psi of boost. The company lists forged pistons for the HO engine and rates it at 550 horsepower." },
      { type: "paragraph", text: "This is a serious performance powertrain." },
      { type: "paragraph", text: "And if the aftermarket embraces the platform, things could get interesting quickly." },
      { type: "paragraph", text: "Turbocharged engines have a long history of responding to calibration, fueling, cooling and airflow changes. Exactly how far owners can reliably push this particular combination remains something that needs to be proven over time—not guessed from dyno-day optimism." },
      { type: "paragraph", text: "That's part of what makes this Charger worth watching." },
      { type: "paragraph", text: "Give the platform to actual owners." },
      { type: "paragraph", text: "Let people modify them." },
      { type: "paragraph", text: "Let them drag race them at legitimate tracks, autocross them, daily-drive them through Northeast winters and pile real mileage onto them." },
      { type: "paragraph", text: "Then we'll know much more than we do from an argument over cylinder count." },

      { type: "heading", text: "The Real Problem May Be Expectations" },
      { type: "paragraph", text: "The Charger badge comes with baggage." },
      { type: "paragraph", text: "Good baggage, mostly." },
      { type: "paragraph", text: "For years Dodge leaned aggressively into HEMI power, Hellcats, Scat Packs, smoky burnouts and an unapologetically old-school interpretation of American performance." },
      { type: "paragraph", text: "Dodge helped train its customers to associate the brand with big-displacement V8 attitude." },
      { type: "paragraph", text: "Then the formula changed." },
      { type: "paragraph", text: "You can't spend years telling enthusiasts the V8 is central to the party and act surprised when some of them notice it's gone." },
      { type: "paragraph", text: "That doesn't automatically make the new car bad." },
      { type: "paragraph", text: "It makes the sales pitch harder." },
      { type: "paragraph", text: "The new Charger isn't entering the market with a blank slate. It's being measured against memories of 392s, Hellcats and cars that made their presence known before they ever reached the stoplight." },
      { type: "paragraph", text: "That's a brutal comparison for any straight-six." },

      { type: "heading", text: "And No, a Charger HEMI Return Isn't Confirmed Yet" },
      { type: "paragraph", text: "This is where rumor needs to stay labeled rumor." },
      { type: "paragraph", text: "There has been plenty of speculation about V8 power eventually returning to the new Charger. The HEMI itself has not disappeared from Stellantis entirely, which naturally keeps the conversation alive." },
      { type: "paragraph", text: "But as of this writing, Dodge's official Charger lineup identifies the gas-powered R/T and Scat Pack with 420- and 550-horsepower SIXPACK engines, alongside the electric Charger Daytona. Dodge has not officially confirmed a new-production HEMI Charger on its current Charger product pages." },
      { type: "paragraph", text: "Could that change?" },
      { type: "paragraph", text: "Absolutely." },
      { type: "paragraph", text: "Until Dodge says it, though, renderings, unnamed-source reports and forum certainty are not the same thing as a production announcement." },
      { type: "paragraph", text: "We've been down that road before." },
      { type: "paragraph", text: "Rumor is fine." },
      { type: "paragraph", text: "Calling rumor fact isn't." },

      { type: "heading", text: "Maybe We're Asking the Wrong Question" },
      { type: "paragraph", text: "Here's where the Charger debate gets more interesting than another V8-versus-six-cylinder shouting match." },
      { type: "paragraph", text: "Maybe the question isn't:" },
      { type: "paragraph", text: "“Can a six-cylinder be a muscle car?”" },
      { type: "paragraph", text: "Of course it can be fast enough." },
      { type: "paragraph", text: "Maybe the better question is:" },
      { type: "paragraph", text: "What exactly are we paying for when we buy an enthusiast car?" },
      { type: "paragraph", text: "If outright speed wins, the SIXPACK has a strong argument." },
      { type: "paragraph", text: "If sound, mechanical character and tradition matter just as much, the V8 crowd isn't being irrational. They're measuring the car differently." },
      { type: "paragraph", text: "And if you're the type who sees 550 turbocharged horsepower and immediately starts wondering what an intercooler, tune, exhaust and better fuel might do?" },
      { type: "paragraph", text: "You're measuring it differently again." },
      { type: "paragraph", text: "That's the part worth preserving in automotive culture." },
      { type: "paragraph", text: "Different builds. Different priorities. Different answers." },

      { type: "heading", text: "Our Take" },
      { type: "paragraph", text: "Writing off the Dodge Charger Hurricane because it doesn't have eight cylinders is too easy." },
      { type: "paragraph", text: "So is telling longtime Charger owners they're supposed to stop caring about the V8 because the new car posts better numbers." },
      { type: "paragraph", text: "The SIXPACK deserves the chance to prove itself on its own merits." },
      { type: "paragraph", text: "Drive it. Modify it. Race it where racing belongs. Put miles on it. Find out what breaks, what responds to tuning and whether the car still makes you look back after shutting the door." },
      { type: "paragraph", text: "That's how enthusiast cars earn reputations." },
      { type: "paragraph", text: "Not through corporate launch copy." },
      { type: "paragraph", text: "And not through internet nostalgia alone." },
      { type: "paragraph", text: "The Charger has plenty of horsepower." },
      { type: "paragraph", text: "Now it has to prove it has enough character to make people care." },
      { type: "paragraph", text: "Here's the question: if a 550-horsepower SIXPACK Charger outruns the V8 Charger you loved but never sounds or feels quite the same, are you taking the faster car—or waiting for eight cylinders?" },
    ],
  },
  {
    slug: "2027-corvette-grand-sport-does-it-need-z52",
    title: "Does the 2027 Corvette Grand Sport Really Need Z52 to Be a Track Car?",
    seoTitle: "2027 Corvette Grand Sport: Does It Need Z52?",
    excerpt:
      "Chevy says the 2027 Corvette Grand Sport blends street manners with track-ready engineering—but its Z52 packages are where the serious track hardware shows up. So should Z52 really be optional on a car called Grand Sport?",
    metaDescription:
      "Does the 2027 Corvette Grand Sport need Z52 for track use? We break down what Chevy confirms, what owners are debating, and what the badge should mean.",
    category: "Gear",
    date: "2026-08-20",
    image: { src: "/img/blog/corvette-grand-sport-z52.jpg", alt: "Does The 2027 Corvette Grand Sport Really Need Z52 To Be A Track Car? — a Grand Sport on a race track with a Base GS vs Z52 Packages callout" },
    body: [
      { type: "heading", text: "The Grand Sport Badge Comes With Expectations" },
      { type: "paragraph", text: "There are certain names you don't slap onto a car casually." },
      { type: "paragraph", text: "Z06." },
      { type: "paragraph", text: "GT3." },
      { type: "paragraph", text: "Shelby." },
      { type: "paragraph", text: "Grand Sport." },
      { type: "paragraph", text: "The **2027 Corvette Grand Sport** especially carries some baggage—in a good way. The original C2 Grand Sports were built around racing, and later versions of the car became the Corvette for people who wanted more chassis and tire than a base car without going all the way into the most expensive, most extreme version." },
      { type: "paragraph", text: "So when Chevrolet brought the name back for 2027, the pitch made sense." },
      { type: "paragraph", text: "The new Grand Sport starts at **$86,000** before destination, gets the wide-body C8 chassis, Magnetic Ride Control, 535 horsepower from Chevrolet's new naturally aspirated 6.7-liter LS6 V8, and is marketed by Chevrolet as a car blending everyday usability with track-focused engineering." },
      { type: "paragraph", text: "Sounds like a Grand Sport." },
      { type: "paragraph", text: "Then owners started reading the fine print." },

      { type: "heading", text: "The 2027 Corvette Grand Sport Z52 Question" },
      { type: "paragraph", text: "A CorvetteForum discussion has been digging into language attributed to the 2027 Corvette owner's manual regarding **track events and competitive driving**." },
      { type: "paragraph", text: "According to the manual language posted by multiple forum members, Grand Sport models equipped with **Z52 performance packages** are specifically listed among the Corvette configurations that can be used for track events and competitive driving." },
      { type: "paragraph", text: "That's where people started asking the obvious question:" },
      { type: "paragraph", text: "**What about the base Grand Sport?**" },
      { type: "paragraph", text: "We need to be precise here." },
      { type: "paragraph", text: "We were able to verify that Chevrolet's Corvette owner site links directly to the owner's manual and tells owners to use the track-preparation materials before track use. The current linked PDF wasn't retrievable through Chevrolet's site during our research, so we're not going to pretend we independently confirmed that exact sentence directly from the PDF." },
      { type: "paragraph", text: "But the same manual wording is reproduced across multiple CorvetteForum discussions." },
      { type: "paragraph", text: "So the owner concern is real." },
      { type: "paragraph", text: "What we **cannot** responsibly say is:" },
      { type: "paragraph", text: "“Chevy says the base Grand Sport is banned from the racetrack.”" },
      { type: "paragraph", text: "That's stronger than the evidence supports." },
      { type: "paragraph", text: "What we can say is that Chevrolet clearly distinguishes the base Grand Sport from the Z52-equipped cars when talking about the serious stuff." },
      { type: "paragraph", text: "And Chevrolet's own engineering descriptions make the distinction even clearer." },

      { type: "heading", text: "Chevy Built Three Different Grand Sports on Purpose" },
      { type: "paragraph", text: "This part isn't rumor." },
      { type: "paragraph", text: "Chevrolet says the base Grand Sport uses a **Touring Suspension**, standard Magnetic Ride Control, Michelin Pilot Sport All Season tires, and a lower-dust braking package." },
      { type: "paragraph", text: "Chevy's own engineers describe that version as the road-trip, canyon-road, everyday Grand Sport." },
      { type: "paragraph", text: "Then comes the **Z52 Sport Performance Package**." },
      { type: "paragraph", text: "That gets Michelin Pilot Sport 4S summer tires, a stiffer suspension tune, Performance Traction Management, and higher-performance iron brakes borrowed from the Z06 hardware family." },
      { type: "paragraph", text: "And this is important:" },
      { type: "paragraph", text: "Chevrolet specifically describes the Z52 Sport car as being intended for the enthusiast who plans to take the Grand Sport to the track." },
      { type: "paragraph", text: "Then there's another step." },
      { type: "paragraph", text: "The **Z52 Track Performance Package** gets carbon-ceramic brakes, Michelin Pilot Sport Cup 2 R tires, carbon-fiber aero, track-focused chassis tuning, and the quad center-exit exhaust." },
      { type: "paragraph", text: "That's the hammer." },
      { type: "paragraph", text: "But notice what Chevy did here." },
      { type: "paragraph", text: "It didn't build one Grand Sport and then offer a cosmetic option package." },
      { type: "paragraph", text: "It built three different levels of intent." },

      { type: "heading", text: "No, You Don't Need the Full Z52 Track Package" },
      { type: "paragraph", text: "This is where the headline can get screwed up fast." },
      { type: "paragraph", text: "If you're hearing:" },
      { type: "paragraph", text: "**“You have to buy carbon ceramics and Cup 2 Rs just to track the new Grand Sport,”**" },
      { type: "paragraph", text: "that's not what the available information shows." },
      { type: "paragraph", text: "There are **two Z52 packages**." },
      { type: "paragraph", text: "The Z52 Sport package is already the step Chevrolet positions toward track-day buyers. The full Z52 Track package is the more specialized configuration." },
      { type: "paragraph", text: "That's a major difference." },
      { type: "paragraph", text: "Chevrolet even entered a preproduction Grand Sport in the 2026 One Lap of America running the **Z52 Sport Performance Package**, not the full Track package." },
      { type: "paragraph", text: "That car finished **seventh overall and second in its class** after competing in road-course sessions, autocross, skidpad events, and long highway transits." },
      { type: "paragraph", text: "So let's kill one piece of potential clickbait right now:" },
      { type: "paragraph", text: "**You apparently do not need the most extreme Z52 package to have a serious track-capable Grand Sport.**" },
      { type: "paragraph", text: "The Z52 Sport package is clearly meant to do that job." },

      { type: "heading", text: "But Should a Grand Sport Need Any Package?" },
      { type: "paragraph", text: "Now we get to the actual argument." },
      { type: "paragraph", text: "And this is where we think Corvette owners have a point." },
      { type: "paragraph", text: "The base 2027 Grand Sport isn't some soft luxury coupe with a Corvette badge glued onto it." },
      { type: "paragraph", text: "It has 535 horsepower." },
      { type: "paragraph", text: "A wide body." },
      { type: "paragraph", text: "Forged wheels." },
      { type: "paragraph", text: "Magnetic Ride Control." },
      { type: "paragraph", text: "Serious brakes." },
      { type: "paragraph", text: "A mid-engine chassis." },
      { type: "paragraph", text: "Chevrolet itself describes the Grand Sport as being as capable on the track as it is on the street." },
      { type: "paragraph", text: "So when you tell a buyer:" },
      { type: "paragraph", text: "“Here's your Grand Sport.”" },
      { type: "paragraph", text: "Then add:" },
      { type: "paragraph", text: "“If you're actually planning track events, we'd steer you toward Z52.”" },
      { type: "paragraph", text: "You can understand why somebody scratches their head." },
      { type: "paragraph", text: "Especially when the car starts at eighty-six grand." },

      { type: "heading", text: "There's Also a Reason Chevy Did It" },
      { type: "paragraph", text: "Now for the other side." },
      { type: "paragraph", text: "Because Chevrolet isn't necessarily being unreasonable here." },
      { type: "paragraph", text: "The base Grand Sport comes on **all-season tires**." },
      { type: "paragraph", text: "That's the first clue." },
      { type: "paragraph", text: "Chevrolet wants that car to work in more conditions, ride comfortably, create less brake dust, and function as the Corvette you can actually drive everywhere." },
      { type: "paragraph", text: "That's probably the version a lot of owners should buy." },
      { type: "paragraph", text: "Realistically, plenty of Grand Sports will spend their lives doing highway miles, back roads, Cars & Coffee, dinner runs, and the occasional hard pull—not 20-minute track sessions cooking tires and brakes." },
      { type: "paragraph", text: "There's nothing wrong with that." },
      { type: "paragraph", text: "And if Chevy can offer those buyers better road manners while letting actual track-day people choose the proper brakes, tires, suspension calibration, and cooling prep they need, there is a legitimate engineering argument for doing it this way." },
      { type: "paragraph", text: "The issue isn't capability." },
      { type: "paragraph", text: "It's the **name**." },

      { type: "heading", text: "Grand Sport Used to Mean Something Pretty Specific" },
      { type: "paragraph", text: "Grand Sport has always lived in the middle." },
      { type: "paragraph", text: "Not just in price." },
      { type: "paragraph", text: "In purpose." },
      { type: "paragraph", text: "More serious than the base Corvette." },
      { type: "paragraph", text: "Less extreme than the top-tier track weapon." },
      { type: "paragraph", text: "That's exactly why people loved the C6 and C7 versions." },
      { type: "paragraph", text: "They were cars you could drive to work, drive across the state, then show up at a track day and beat on without feeling like you'd brought the wrong Corvette." },
      { type: "paragraph", text: "That identity is what Chevrolet is trying to preserve with the new one." },
      { type: "paragraph", text: "And frankly, the **Z52 Sport Grand Sport sounds like the true spiritual successor**." },
      { type: "paragraph", text: "You've still got the naturally aspirated V8." },
      { type: "paragraph", text: "You don't need carbon ceramics." },
      { type: "paragraph", text: "You don't need Cup 2 Rs." },
      { type: "paragraph", text: "You don't need maximum aero hanging off the car." },
      { type: "paragraph", text: "But you do get the serious brakes, summer rubber, firmer chassis calibration, and Performance Traction Management that make sense when you're running lap after lap." },
      { type: "paragraph", text: "That's the sweet spot." },
      { type: "paragraph", text: "Which is exactly what Grand Sport is supposed to be." },

      { type: "heading", text: "The Base Car Might Actually Need a Different Label" },
      { type: "paragraph", text: "Here's where we'll make the slightly unpopular argument." },
      { type: "paragraph", text: "The problem may not be that Chevrolet requires Z52 for the full Grand Sport track mission." },
      { type: "paragraph", text: "The problem might be that the **base configuration wears the same Grand Sport badge**." },
      { type: "paragraph", text: "Mechanically, the Touring version makes sense." },
      { type: "paragraph", text: "Marketing-wise?" },
      { type: "paragraph", text: "It muddies the story." },
      { type: "paragraph", text: "Chevy itself calls the Grand Sport an “all-around athlete,” while the Z06 is positioned as “track born, street ready.”" },
      { type: "paragraph", text: "Fair enough." },
      { type: "paragraph", text: "But if the base Grand Sport is deliberately optimized around all-season tires, quieter brakes, road trips, and street use, maybe buyers are justified in expecting the track-oriented hardware to be standard when the car wears one of Corvette's most historically competition-linked names." },
      { type: "paragraph", text: "That's not outrage." },
      { type: "paragraph", text: "It's just an identity question." },

      { type: "heading", text: "What We Know—and What We Don't" },
      { type: "paragraph", text: "**Confirmed:** The 2027 Corvette Grand Sport starts at $86,000 before destination and uses a 535-hp 6.7-liter naturally aspirated V8. The base car uses all-season tires and Touring-oriented chassis tuning. The Z52 Sport package adds summer tires, stronger iron brakes, firmer suspension tuning, and Performance Traction Management. The Z52 Track package goes further with carbon ceramics, Cup 2 R tires, carbon aero, and more focused chassis tuning. Chevrolet itself used a Z52 Sport Grand Sport—not the full Track package—to compete successfully in One Lap of America." },
      { type: "paragraph", text: "**Strongly supported, but worth reading carefully:** Multiple CorvetteForum owners have reproduced 2027 owner's-manual language identifying Z52-equipped Grand Sports for track events and competitive driving. We were not able to independently retrieve the currently linked Chevrolet PDF during this research, so we're not going to turn that wording into a warranty conclusion the source material doesn't explicitly establish." },
      { type: "paragraph", text: "**Not confirmed:** That taking a non-Z52 Grand Sport onto a racetrack automatically voids your warranty. That the base Grand Sport physically cannot handle a track day. That you need the full Z52 Track Performance Package just to run HPDE events." },
      { type: "paragraph", text: "Those are three very different claims." },
      { type: "paragraph", text: "Don't combine them." },

      { type: "heading", text: "So Does the Grand Sport Need Z52?" },
      { type: "paragraph", text: "For somebody who actually plans to track the car?" },
      { type: "paragraph", text: "**We'd order Z52 Sport.**" },
      { type: "paragraph", text: "Not because the base car suddenly becomes incapable the moment it crosses pit lane." },
      { type: "paragraph", text: "Because the package gives you the equipment we'd want anyway: better brakes, proper summer tires, firmer chassis tuning, and the electronics calibrated around that mission." },
      { type: "paragraph", text: "The full Z52 Track package?" },
      { type: "paragraph", text: "That's different." },
      { type: "paragraph", text: "Cup 2 Rs, carbon ceramics, and serious aero make a lot more sense for somebody chasing lap times than somebody planning two HPDE weekends a year." },
      { type: "paragraph", text: "Buy the car for what you're actually going to do with it." },
      { type: "paragraph", text: "That's advice that works whether we're talking Corvettes, Jeeps, UTVs, or anything else with tires." },
      { type: "paragraph", text: "But Chevrolet created this debate itself by putting the **Grand Sport** name on a Touring-spec version and then reserving the clearer track mission for Z52." },
      { type: "paragraph", text: "So here's the question we'd put to Corvette owners:" },
      { type: "paragraph", text: "**If you were ordering an $86,000-plus Grand Sport tomorrow, would you consider Z52 Sport mandatory because of what the Grand Sport badge should represent—or would you rather keep the all-season Touring setup and spend the money elsewhere?**" },
    ],
  },
  {
    slug: "cfmoto-vs-polaris-vs-can-am-what-are-you-paying-for",
    title: "CFMOTO vs Polaris vs Can-Am: What Are You Actually Paying For?",
    seoTitle: "CFMOTO vs Polaris vs Can-Am: What Are You Paying For?",
    excerpt:
      "CFMOTO keeps closing the gap while Polaris and Can-Am keep commanding premium prices. So what are you actually buying with the extra money—better hardware, better support, or just the badge?",
    metaDescription:
      "CFMOTO vs Polaris vs Can-Am: compare price, reliability, dealer support, resale and what UTV owners say you're really paying for.",
    category: "Gear",
    date: "2026-08-24",
    image: { src: "/img/blog/cfmoto-vs-polaris-vs-canam.jpg", alt: "CFMOTO vs Polaris vs Can-Am: What Are You Actually Paying For? — three UTVs lined up in the mud" },
    body: [
      { type: "paragraph", text: "Here's the question that keeps coming up:" },
      { type: "paragraph", text: "**If a CFMOTO gives you most of the same equipment for thousands less, what exactly are you paying extra for when you buy a Polaris Ranger or Can-Am Defender?**" },
      { type: "paragraph", text: "That's where the **CFMOTO vs Polaris vs Can-Am** argument gets interesting." },
      { type: "paragraph", text: "Because this isn't really a horsepower comparison anymore. CFMOTO has closed enough of the equipment and performance gap that buyers aren't automatically dismissing it as the cheap alternative." },
      { type: "paragraph", text: "Now they're asking whether the premium brands are actually better—or just more expensive." },
      { type: "paragraph", text: "And owners don't agree." },

      { type: "heading", text: "CFMOTO vs Polaris vs Can-Am Isn't Just About MSRP" },
      { type: "paragraph", text: "Walk around a newer CFMOTO UForce and the value proposition is pretty obvious." },
      { type: "paragraph", text: "You can get a lot of machine for the money. Features that might require packages, accessories or a higher trim elsewhere can be sitting there from day one." },
      { type: "paragraph", text: "That's exactly why the discussion has changed." },
      { type: "paragraph", text: "In a recent r/UTV ownership debate, buyers compared the UForce U10 directly against the Polaris Ranger and Can-Am Defender. One owner described a roughly **C$22,000 versus C$30,000** difference when comparing his CFMOTO purchase with a Ranger XP 1000." },
      { type: "paragraph", text: "Eight grand isn't pocket change." },
      { type: "paragraph", text: "That's a trailer. Tires. Winches. Communications gear. Camping equipment. Or a whole lot of fuel." },
      { type: "paragraph", text: "So if the cheaper machine does the same job, CFMOTO starts making a ton of sense." },
      { type: "paragraph", text: "But purchase price isn't the whole ownership experience." },

      { type: "heading", text: "You're Paying for the Dealer Network" },
      { type: "paragraph", text: "This came up repeatedly among actual owners." },
      { type: "paragraph", text: "Polaris and Can-Am have been in the North American SxS market long enough to build large dealer, service and parts networks. That matters when your machine stops moving." },
      { type: "paragraph", text: "An owner in the r/UTV discussion specifically chose Polaris because dealers, OEM parts and aftermarket parts were easier to find in his area. Other owners made similar points about being able to get repairs handled quickly instead of waiting on components or hunting for someone willing to work on the machine." },
      { type: "paragraph", text: "That doesn't mean CFMOTO has no support." },
      { type: "paragraph", text: "Its dealer network has grown significantly, and some owners report excellent warranty experiences—especially when they have a strong local dealer." },
      { type: "paragraph", text: "But that's the part people miss:" },
      { type: "paragraph", text: "**You're not just buying the UTV. You're buying the dealer standing behind it.**" },
      { type: "paragraph", text: "A great CFMOTO dealer five miles away might make the UForce the smarter purchase." },
      { type: "paragraph", text: "A weak dealer two hours away might completely change that equation." },

      { type: "heading", text: "Reliability Is Where the Arguments Get Loud" },
      { type: "paragraph", text: "Search long enough and you'll find somebody who has destroyed every brand." },
      { type: "paragraph", text: "There are Polaris owners with thousands of trouble-free miles." },
      { type: "paragraph", text: "There are Polaris owners who have replaced engines." },
      { type: "paragraph", text: "There are Can-Am owners who swear they'll never own anything else." },
      { type: "paragraph", text: "And there are CFMOTO owners beating their machines through work, snow and trails with no major problems." },
      { type: "paragraph", text: "One CFMOTO ATV owner recently described running a 2022 machine hard for utility work—plowing, pulling trailers and hauling wood—with no reported issues. Another UTV owner said his CFMOTO had been in the shop six or seven times for problems involving sensors, the fuel system, stator, front differential and other components." },
      { type: "paragraph", text: "Those experiences are real." },
      { type: "paragraph", text: "They're also individual experiences." },
      { type: "paragraph", text: "That's important." },
      { type: "paragraph", text: "One blown engine doesn't prove Polaris is unreliable. One flawless CFMOTO doesn't prove the brand has completely erased the long-term durability question." },
      { type: "paragraph", text: "What matters is the pattern over thousands of machines and years of ownership." },
      { type: "paragraph", text: "And that's where Polaris and Can-Am still have an advantage: **there's simply more long-term ownership history to examine.**" },

      { type: "heading", text: "What About Resale?" },
      { type: "paragraph", text: "This is where the cheaper purchase price can come back into the conversation later." },
      { type: "paragraph", text: "Established brands generally benefit from stronger name recognition in the used market. Buyers know what a Ranger is. They know the Defender. There are years of used machines, parts, accessories and community knowledge behind them." },
      { type: "paragraph", text: "CFMOTO is improving here, but owners still regularly mention resale as part of the premium-brand advantage. Even dealers comparing the brands tend to frame CFMOTO around upfront value while Polaris and Can-Am benefit from stronger long-term market recognition and parts ecosystems." },
      { type: "paragraph", text: "But resale only matters if you're selling." },
      { type: "paragraph", text: "If you plan on buying a machine, maintaining it and running it into the ground for ten years?" },
      { type: "paragraph", text: "That changes the math." },
      { type: "paragraph", text: "Paying $5,000 or $8,000 less upfront can be pretty powerful." },

      { type: "heading", text: "The Aftermarket Is Part of the Price Too" },
      { type: "paragraph", text: "Jeep people already understand this." },
      { type: "paragraph", text: "You don't just buy the vehicle." },
      { type: "paragraph", text: "You buy into an ecosystem." },
      { type: "paragraph", text: "Polaris has an enormous accessory and aftermarket catalog. Can-Am isn't exactly hurting either." },
      { type: "paragraph", text: "Doors. Windshields. Suspension. Clutches. Wheels. Storage. Cab systems. Plows. Audio. Lighting. Replacement parts." },
      { type: "paragraph", text: "CFMOTO's aftermarket continues to grow, but the older brands still have the advantage when you want three different versions of the same weird bracket delivered by Friday." },
      { type: "paragraph", text: "That convenience has value." },
      { type: "paragraph", text: "How much value depends entirely on how you use your machine." },

      { type: "heading", text: "So Is CFMOTO the Better Deal?" },
      { type: "paragraph", text: "Sometimes." },
      { type: "paragraph", text: "That's the answer nobody likes because it doesn't start a brand war." },
      { type: "paragraph", text: "If you're looking at a **CFMOTO UForce**, the machine has the features you want, you've got a good local dealer and the price difference is substantial?" },
      { type: "paragraph", text: "We wouldn't dismiss it because somebody on the internet still thinks CFMOTO is the same company it was ten years ago." },
      { type: "paragraph", text: "But if you're running a machine every week, depending on it for work, modifying it heavily or keeping it somewhere downtime becomes a real problem?" },
      { type: "paragraph", text: "That Polaris or Can-Am premium starts buying something tangible." },
      { type: "paragraph", text: "**Parts. Dealers. Aftermarket support. Ownership history. Resale.**" },
      { type: "paragraph", text: "Not just a logo." },

      { type: "heading", text: "Buy the Machine—and the Support Behind It" },
      { type: "paragraph", text: "The wrong way to compare these machines is:" },
      { type: "paragraph", text: "**“Which one has the biggest number on the spec sheet?”**" },
      { type: "paragraph", text: "The better question is:" },
      { type: "paragraph", text: "**“What happens three years after I buy it?”**" },
      { type: "paragraph", text: "Who fixes it?" },
      { type: "paragraph", text: "How fast can you get the part?" },
      { type: "paragraph", text: "Can you modify it the way you want?" },
      { type: "paragraph", text: "What's it worth when you sell it?" },
      { type: "paragraph", text: "And how much money did you save—or spend—getting there?" },
      { type: "paragraph", text: "CFMOTO is forcing Polaris and Can-Am to answer those questions because the price gap is getting harder to ignore." },
      { type: "paragraph", text: "That's good for buyers." },
      { type: "paragraph", text: "So here's ours:" },
      { type: "paragraph", text: "**Would you rather save $5,000–$8,000 upfront on a well-equipped CFMOTO, or spend more for the dealer network, aftermarket and resale behind a Polaris or Can-Am?**" },
      { type: "paragraph", text: "If you've actually owned one of these machines, we want to hear the experience—not the brand loyalty." },
      { type: "paragraph", text: "Tell us what broke, what didn't, what the dealer did about it, and whether you'd buy the same machine again." },
      { type: "paragraph", text: "That's the information that actually helps somebody spend their money." },
    ],
  },
  {
    slug: "jeep-gladiator-392-stop-calling-rumors-facts",
    title: "Jeep Gladiator 392: Stop Calling Rumors Facts",
    excerpt:
      "Everyone keeps saying the Jeep Gladiator 392 is confirmed—but the details aren't nearly that simple. We separate what Jeep has actually said from the rumors, assumptions, and enthusiast wish lists.",
    metaDescription:
      "The Jeep Gladiator 392 hype is everywhere. Here's what Jeep has actually confirmed, what remains speculation, and what owners should watch next.",
    category: "Gear",
    date: "2026-09-03",
    image: { src: "/img/blog/gladiator-392-rumors.jpg", alt: "Gladiator 392 — Stop Calling Rumors Facts: a lifted Jeep Gladiator Rubicon on 37s kicking up dust" },
    body: [
      { type: "paragraph", text: "The **Jeep Gladiator 392** is confirmed." },
      { type: "paragraph", text: "Except maybe it isn't." },
      { type: "paragraph", text: "That's the problem." },
      { type: "paragraph", text: "For more than a year, Jeep forums, enthusiast pages, YouTube channels, and social feeds have been repeating some version of the same headline: **“392 Gladiator confirmed.”**" },
      { type: "paragraph", text: "And look—we want one too." },
      { type: "paragraph", text: "A factory V8 Gladiator makes almost too much sense. You get the removable doors, solid axles, truck bed, trail capability, and then you drop a Hemi into the middle of it." },
      { type: "paragraph", text: "That's basically Asphalt and Dirt in vehicle form." },
      { type: "paragraph", text: "But wanting something to be true and having Jeep officially put it on an order sheet are two different things." },
      { type: "paragraph", text: "Right now, enthusiasts need to stop treating those two things like they're the same." },

      { type: "heading", text: "What Jeep Has Actually Said About a V8 Gladiator" },
      { type: "paragraph", text: "The hype really took off after Jeep CEO Bob Broderdorf made comments in 2025 about the future of Hemi power within the Jeep lineup." },
      { type: "paragraph", text: "He made it clear that the 6.4-liter Hemi still had a home at Jeep and specifically reassured Wrangler and Gladiator fans that Hemi wasn't disappearing from the conversation." },
      { type: "paragraph", text: "That was enough to light the fuse." },
      { type: "paragraph", text: "The Jeep Gladiator Forum thread built around those comments has now grown to roughly **140 pages, more than 2,000 posts, and over 120 watchers**. Owners are still dissecting every interview, order guide, production rumor, and Stellantis announcement looking for confirmation." },
      { type: "paragraph", text: "That's not a small amount of interest." },
      { type: "paragraph", text: "But here's the key distinction:" },
      { type: "paragraph", text: "**Jeep signaling that a Hemi-powered Gladiator is coming is not the same as Jeep announcing a Gladiator Rubicon 392 with confirmed specifications, pricing, and production dates.**" },
      { type: "paragraph", text: "Those details matter." },

      { type: "heading", text: "The Jeep Gladiator 392 Has Not Been Fully Defined" },
      { type: "paragraph", text: "When most people hear “Gladiator 392,” they picture something very specific." },
      { type: "paragraph", text: "A 6.4-liter Hemi." },
      { type: "paragraph", text: "Roughly Wrangler 392 levels of power." },
      { type: "paragraph", text: "Probably some version of a Rubicon or Mojave." },
      { type: "paragraph", text: "Heavy-duty axles." },
      { type: "paragraph", text: "Big brakes." },
      { type: "paragraph", text: "Aggressive suspension." },
      { type: "paragraph", text: "And a price tag that hurts just enough to make us complain about it before buying one anyway." },
      { type: "paragraph", text: "The problem is that Jeep has not publicly locked all of that down." },
      { type: "paragraph", text: "Even inside the major Gladiator forum discussion, owners have questioned whether the eventual V8 could actually be a **5.7-liter Hemi instead of the 6.4-liter 392**. Others have pointed out that recent Stellantis presentations and executive comments haven't always used “392” when discussing future Gladiator powertrains." },
      { type: "paragraph", text: "That doesn't mean the 392 isn't coming." },
      { type: "paragraph", text: "It means we don't know enough yet to present it as finished fact." },

      { type: "heading", text: "The 2027 Jeep Gladiator Order Information Matters" },
      { type: "paragraph", text: "This is where things get interesting." },
      { type: "paragraph", text: "As of late August 2026, enthusiasts are already discussing updated **2027 Jeep Gladiator order-guide information**." },
      { type: "paragraph", text: "There are new equipment combinations, trim changes, colors, and ongoing speculation about future models." },
      { type: "paragraph", text: "What isn't sitting there as a normal, clearly orderable production vehicle?" },
      { type: "paragraph", text: "A Gladiator 392." },
      { type: "paragraph", text: "The 2027 order-guide discussions are active right now, and owners are already debating missing trims and packages." },
      { type: "paragraph", text: "At the same time, Jeep's own current Gladiator page is teasing additional upcoming “Classified” models as part of its 2027 lineup campaign. Jeep isn't identifying those vehicles yet." },
      { type: "paragraph", text: "Could one be the V8?" },
      { type: "paragraph", text: "Absolutely." },
      { type: "paragraph", text: "Can we call that confirmation?" },
      { type: "paragraph", text: "No." },
      { type: "paragraph", text: "That's exactly how rumors turn into “facts.”" },
      { type: "paragraph", text: "Someone sees a blank space." },
      { type: "paragraph", text: "Someone connects it to a CEO comment." },
      { type: "paragraph", text: "Another account posts “392 CONFIRMED.”" },
      { type: "paragraph", text: "Ten reposts later, everybody thinks Jeep issued a press release." },

      { type: "heading", text: "Why Jeep Owners Want the V8 So Badly" },
      { type: "paragraph", text: "The obsession isn't hard to understand." },
      { type: "paragraph", text: "The Gladiator has always had the chassis and personality for more power." },
      { type: "paragraph", text: "The 3.6-liter Pentastar gets the job done, but once you start adding 35s, 37s, armor, bumpers, recovery equipment, camping gear, and everything else we bolt onto these trucks, 285 horsepower starts feeling a lot less exciting." },
      { type: "paragraph", text: "And the Hemi solves more than a horsepower problem." },
      { type: "paragraph", text: "It's the sound." },
      { type: "paragraph", text: "The throttle response." },
      { type: "paragraph", text: "The simplicity and familiarity enthusiasts associate with a naturally aspirated V8." },
      { type: "paragraph", text: "The fact that a ridiculous engine in an equally ridiculous removable-roof pickup just feels right." },
      { type: "paragraph", text: "Forum owners are even debating whether they'd rather have a traditional Hemi than a more powerful Hurricane inline-six because horsepower isn't the only part of the ownership equation." },
      { type: "paragraph", text: "That's a real conversation." },

      { type: "heading", text: "Then There's the Price" },
      { type: "paragraph", text: "This might decide whether the Hemi Gladiator becomes a hero or another vehicle everybody loves but few people buy." },
      { type: "paragraph", text: "The Wrangler 392 proved Jeep enthusiasts will spend serious money for V8 power." },
      { type: "paragraph", text: "But the Gladiator market is different." },
      { type: "paragraph", text: "It's already competing against midsize pickups that can tow, haul, and daily-drive extremely well for substantially less money." },
      { type: "paragraph", text: "The forum discussion keeps circling back to the same question:" },
      { type: "paragraph", text: "**How much extra should a V8 really cost?**" },
      { type: "paragraph", text: "Some owners argue that adding tens of thousands of dollars for the engine turns the whole thing into a luxury toy. Others say a factory Hemi, warranty, upgraded drivetrain, and resale value justify the premium." },
      { type: "paragraph", text: "That's probably where the real battle will happen." },
      { type: "paragraph", text: "Not whether people want it." },
      { type: "paragraph", text: "Whether enough people want it **at Jeep's price.**" },

      { type: "heading", text: "What We Know, What We Think, and What We Don't Know" },
      { type: "paragraph", text: "Here's where Asphalt and Dirt stands." },
      { type: "paragraph", text: "**We know:** Jeep leadership has publicly made it clear that Hemi power remains part of Jeep's future and has specifically included Gladiator fans in that conversation." },
      { type: "paragraph", text: "**We have strong reason to believe:** A factory V8 Gladiator is a serious possibility and may be part of upcoming product announcements." },
      { type: "paragraph", text: "**We do not know:**" },
      { type: "paragraph", text: "The final engine displacement." },
      { type: "paragraph", text: "The final trim." },
      { type: "paragraph", text: "Horsepower." },
      { type: "paragraph", text: "Torque." },
      { type: "paragraph", text: "Axle package." },
      { type: "paragraph", text: "Suspension." },
      { type: "paragraph", text: "Towing capacity." },
      { type: "paragraph", text: "Price." },
      { type: "paragraph", text: "Actual order date." },
      { type: "paragraph", text: "Actual production date." },
      { type: "paragraph", text: "Until Jeep publishes those details, they're not facts." },
      { type: "paragraph", text: "They're educated guesses." },

      { type: "heading", text: "Stop Killing the Story by Pretending We Already Know It" },
      { type: "paragraph", text: "Here's the funny part." },
      { type: "paragraph", text: "The actual story is better than the rumor." },
      { type: "paragraph", text: "Jeep has a product enthusiasts have begged for almost since the Gladiator launched." },
      { type: "paragraph", text: "The Hemi is alive again." },
      { type: "paragraph", text: "Jeep is teasing future Gladiator models." },
      { type: "paragraph", text: "The community is watching every move." },
      { type: "paragraph", text: "And we genuinely don't know exactly what Jeep is about to do." },
      { type: "paragraph", text: "That's interesting." },
      { type: "paragraph", text: "We don't need to manufacture certainty where it doesn't exist." },
      { type: "paragraph", text: "If Jeep announces a 470-horsepower Gladiator Rubicon 392 tomorrow, we'll be right there talking about it." },
      { type: "paragraph", text: "But until the build sheet exists, let's call it what it is:" },
      { type: "paragraph", text: "**A V8 Gladiator looks increasingly likely.**" },
      { type: "paragraph", text: "A fully confirmed **Jeep Gladiator 392** with known specs, pricing, and production?" },
      { type: "paragraph", text: "Not yet." },
      { type: "paragraph", text: "And now the important question:" },
      { type: "paragraph", text: "**If Jeep gives us the V8 Gladiator, what would you actually pay for it?**" },
      { type: "paragraph", text: "Would you spend Wrangler 392 money?" },
      { type: "paragraph", text: "Or does Jeep need to keep this thing under control for it to make sense?" },
      { type: "paragraph", text: "Let us know." },
      { type: "paragraph", text: "Because if this truck finally drops, the price might start a bigger fight than the engine ever did." },
    ],
  },
  {
    slug: "california-tire-rules-what-enthusiasts-need-to-know",
    title: "California Tire Rules: What Enthusiasts Actually Need to Know",
    seoTitle: "California Tire Rules: What Enthusiasts Need to Know",
    excerpt:
      "California didn't ban your 37s—but its new tire rules could still matter to Jeep, off-road and performance owners. Here's what the regulation actually says, what it doesn't, and what enthusiasts should be watching.",
    metaDescription:
      "California tire rules are changing. Here's what the new standards actually mean for off-road tires, performance tires, 35s, 37s and more.",
    category: "Culture",
    date: "2026-08-31",
    image: { src: "/img/blog/california-tire-rules.jpg", alt: "California Tire Rules: What It Really Means — a muddy Jeep Rubicon on 37s next to a crossed-out tire graphic" },
    body: [
      { type: "paragraph", text: "No, California did not just ban your 37s." },
      { type: "paragraph", text: "It didn't outlaw lifted Jeeps. It didn't require everybody to run factory-size tires. And nobody from Sacramento is coming to measure the rubber under your Wrangler." },
      { type: "paragraph", text: "But the **California tire rules** that were approved in August are real, and if you're into Jeeps, off-roading, street builds or track cars, they're worth paying attention to." },
      { type: "paragraph", text: "Because underneath some of the social-media outrage is a legitimate question:" },
      { type: "paragraph", text: "**What happens when tire efficiency regulations meet enthusiast vehicles?**" },
      { type: "paragraph", text: "That part is worth talking about." },

      { type: "heading", text: "What California Actually Approved" },
      { type: "paragraph", text: "On August 17, 2026, the California Energy Commission approved its Replacement Tire Efficiency Program, the first state standards of their kind in the country." },
      { type: "paragraph", text: "The rules apply to replacement tires sold for passenger vehicles and light-duty trucks in California. Phase one begins in **2029**, with stricter requirements taking effect in **2033**." },
      { type: "paragraph", text: "The basic idea is straightforward: replacement tires shouldn't dramatically reduce the efficiency a vehicle had when it left the factory." },
      { type: "paragraph", text: "Tires create rolling resistance. More rolling resistance means the engine—or electric motor—needs more energy to keep the vehicle moving. California wants replacement tires to meet minimum efficiency standards while maintaining requirements for wet grip and other performance characteristics." },
      { type: "paragraph", text: "That's the rule." },
      { type: "paragraph", text: "There is nothing in the regulation saying your Jeep has to stay on the tire size printed on the door jamb." },

      { type: "heading", text: "California Tire Rules Aren't Tire-Size Rules" },
      { type: "paragraph", text: "This is where the internet started getting sideways." },
      { type: "paragraph", text: "Some enthusiast discussions quickly turned the regulation into some version of:" },
      { type: "paragraph", text: "**“California is banning oversized tires.”**" },
      { type: "paragraph", text: "That's not what the adopted program says." },
      { type: "paragraph", text: "The rule establishes efficiency requirements for tires being sold. It does **not** establish a maximum 33-, 35-, 37- or 40-inch tire size for your vehicle." },
      { type: "paragraph", text: "There are also exemptions built into the program, including limited-production tires, high-load-index tires and tires that cannot sustain speeds above 50 mph. The California Energy Commission also says accommodations were made for certain specialty categories, including competition tires and some large off-road tires." },
      { type: "paragraph", text: "So can everyone with a Jeep on 37s stop caring?" },
      { type: "paragraph", text: "Not exactly." },

      { type: "heading", text: "The Real Question for Off-Road Tires" },
      { type: "paragraph", text: "The better question isn't:" },
      { type: "paragraph", text: "**“Are they banning 37s?”**" },
      { type: "paragraph", text: "It's:" },
      { type: "paragraph", text: "**“Which 37s will manufacturers still be willing to sell in California once these standards take effect?”**" },
      { type: "paragraph", text: "That's a much more complicated conversation." },
      { type: "paragraph", text: "A 37-inch all-terrain designed for highway use is a very different product from a competition-specific tire or a massive low-speed rock-crawling tire." },
      { type: "paragraph", text: "And that's where enthusiast concerns become legitimate." },
      { type: "paragraph", text: "The CEC's own public rulemaking docket continued receiving comments after the regulation was adopted asking for additional review of specialty-performance tires and raising concerns about off-road tires, consumer choice and cost." },
      { type: "paragraph", text: "Those comments are opinions and concerns—not proof that specific tires will disappear." },
      { type: "paragraph", text: "That distinction matters." },
      { type: "paragraph", text: "Right now, anyone telling you that a specific BFGoodrich, Nitto, Falken, Toyo or Mickey Thompson tire is definitely going to be banned needs to show the actual classification and compliance data for that tire." },
      { type: "paragraph", text: "Otherwise, they're guessing." },

      { type: "heading", text: "Performance Car Owners Should Be Watching Too" },
      { type: "paragraph", text: "This isn't just a Jeep story." },
      { type: "paragraph", text: "Street cars, autocross cars and track builds often live on specialty rubber where outright grip matters far more than fuel economy." },
      { type: "paragraph", text: "Ultra-high-performance tires, 200-treadwear tires, drag-oriented tires and competition tires are all designed around different priorities." },
      { type: "paragraph", text: "California says its testing found the efficiency standards can be met without sacrificing safety, tire lifespan or other important characteristics, and the regulations include separate treatment for several specialty categories." },
      { type: "paragraph", text: "Manufacturers—including major tire companies—were involved during years of stakeholder discussions." },
      { type: "paragraph", text: "Still, enthusiasts have a fair reason to watch what happens next." },
      { type: "paragraph", text: "Because what works technically isn't always the same thing as what manufacturers decide makes financial sense to keep producing." },

      { type: "heading", text: "Could This Spread Beyond California?" },
      { type: "paragraph", text: "This might be the bigger story." },
      { type: "paragraph", text: "California is often large enough as a market that manufacturers don't simply build completely different product lines for the state." },
      { type: "paragraph", text: "If tire manufacturers redesign products to meet California's requirements, some of those changes could eventually affect what gets sold elsewhere." },
      { type: "paragraph", text: "That's not guaranteed." },
      { type: "paragraph", text: "But it's one reason an off-road owner in New Jersey, Pennsylvania or anywhere else shouldn't dismiss this as somebody else's problem." },
      { type: "paragraph", text: "California may be where the regulation started." },
      { type: "paragraph", text: "The tire industry isn't confined by state lines." },

      { type: "heading", text: "There's Another Side to This" },
      { type: "paragraph", text: "It's also worth acknowledging why these rules exist." },
      { type: "paragraph", text: "According to the California Energy Commission, more efficient replacement tires could eventually save California motorists nearly **$1 billion annually** in gasoline and electricity costs." },
      { type: "paragraph", text: "The agency estimates Phase 1 could add around **$6 to the cost of a set of four tires** while producing roughly $85 in energy savings over their life. Phase 2 estimates put the added tire cost around $26 per set against $179 in projected savings." },
      { type: "paragraph", text: "You can agree with the policy, hate the policy or question those projections." },
      { type: "paragraph", text: "But that's the actual argument." },
      { type: "paragraph", text: "Not government-approved 32s versus illegal 37s." },

      { type: "heading", text: "What Asphalt and Dirt Is Watching" },
      { type: "paragraph", text: "For us, three things matter going forward." },
      { type: "paragraph", text: "**Availability.** Do popular enthusiast tires continue being sold without major changes?" },
      { type: "paragraph", text: "**Performance.** Can manufacturers reduce rolling resistance without sacrificing the traction, durability and sidewall strength off-road owners actually need?" },
      { type: "paragraph", text: "**Cost.** Will specialty tires become noticeably more expensive because manufacturers have to redesign, test or certify additional products?" },
      { type: "paragraph", text: "Those answers probably won't come from Facebook memes." },
      { type: "paragraph", text: "They'll come from manufacturers, published compliance information and what eventually shows up—or disappears—from tire racks." },

      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "Your 37s aren't suddenly illegal." },
      { type: "paragraph", text: "Your lifted Jeep isn't being forced back onto stock rubber." },
      { type: "paragraph", text: "And California hasn't outlawed performance tires." },
      { type: "paragraph", text: "But dismissing the entire thing because the loudest claims are wrong would be a mistake too." },
      { type: "paragraph", text: "The **California tire rules** represent a real change in how replacement tires will be regulated, and enthusiast applications sit right where efficiency standards, performance requirements and consumer choice collide." },
      { type: "paragraph", text: "That's a conversation worth having without turning it into panic." },
      { type: "paragraph", text: "So here's the question:" },
      { type: "paragraph", text: "**If a new tire delivered the same traction, durability and off-road performance as the tire you're running now—but used less fuel—would you care?**" },
      { type: "paragraph", text: "Or is tire efficiency something that should stay completely out of enthusiast vehicle culture?" },
      { type: "paragraph", text: "Drop your take. This one is going to get interesting." },
    ],
  },
  {
    slug: "what-makes-a-daily-driver-trail-ready",
    title: "What Makes A Daily Driver Trail Ready",
    excerpt: "Highlights, laughs, and lessons from an epic weekend on red clay and good vibes.",
    category: "Builds",
    date: "2025-05-30",
    image: { src: "/img/builds/rock-rhino.jpg", alt: "Jeep built as a daily driver on a trail" },
  },
  {
    slug: "the-gear-we-actually-use",
    title: "The Gear We Actually Use",
    excerpt: "Our favorite upgrades and gear that actually hold up when the trail gets tough.",
    category: "Gear",
    date: "2025-05-27",
    image: { src: "/img/blog/gear-flatlay.jpg", alt: "Flatlay of off-road recovery gear" },
  },
  {
    slug: "red-clay-run-community-ride-recap",
    title: "Red Clay Run: Community Ride Recap",
    excerpt: "Highlights, laughs, and lessons from an epic weekend on red clay and good vibes.",
    category: "Events",
    date: "2025-05-24",
    image: { src: "/img/blog/trail-convoy.jpg", alt: "Aerial view of a Jeep convoy on a trail" },
  },
  {
    slug: "overland-setup-essentials",
    title: "Overland Setup Essentials",
    excerpt: "The gear, mods, and systems that make long trips smoother.",
    category: "Trail & Travel",
    date: "2025-05-11",
    image: { src: "/img/podcast/ep-convoy.jpg", alt: "Overland-equipped Jeep convoy on a forest road" },
    editorsPick: true,
  },
  {
    slug: "tires-101-choosing-traction",
    title: "Tires 101: Match the Tire to the Mission",
    seoTitle: "How to Choose the Right Tires for Street or Trail",
    excerpt:
      "The toughest-looking or stickiest tire isn't automatically the right one. The best tire is the one that works where your vehicle actually spends its time — without punishing you everywhere else.",
    metaDescription:
      "How to choose the right tires for street, track, trail or overland use — and the grip, noise, weight and wear tradeoffs that come with each.",
    category: "Gear",
    date: "2026-08-12",
    image: {
      src: "/img/blog/tires-101-choosing-traction.jpg",
      alt: "Tires 101: Match The Tire To The Mission — a Mustang on a wet mountain road beside a Bronco climbing a rocky dirt bank",
    },
    editorsPick: true,
    body: [
      { type: "heading", text: "How to Choose the Right Tires: Start With Reality" },
      { type: "paragraph", text: "Tires might be the most consequential modification people buy for the wrong reason." },
      { type: "paragraph", text: "Learning how to choose the right tires starts with an honest inventory of your driving. Not the trail you might run someday. Not the track event you keep threatening to book. Not the build photo saved on your phone." },
      { type: "paragraph", text: "Where will the next 10,000 miles happen?" },
      { type: "paragraph", text: "A car commuting five days a week and attending two track days has different needs than a dedicated time-attack build. A Wrangler driving 90 percent highway miles with occasional forest roads doesn't need the same tire as a rig spending every weekend in deep mud." },
      { type: "paragraph", text: "Match the tire to the mission, not the mood board." },

      { type: "heading", text: "Street Tires: Grip Has a Temperature Range" },
      { type: "paragraph", text: "**Summer and max-performance summer.** Summer tires aren't \"dry-only\" tires. Good max-performance summer tires deliver outstanding wet braking and cornering when the temperature is right, because their compounds and tread designs prioritize warm-weather grip, response, and precision." },
      { type: "paragraph", text: "That temperature qualifier matters." },
      { type: "paragraph", text: "Michelin advises against using its ultra-high-performance summer tires below 40 degrees Fahrenheit and warns that some can crack if flexed below 20 degrees. They're the right tool for a performance street car in warm weather. They're the wrong tool for snow, ice, or a freezing morning commute." },
      { type: "paragraph", text: "Tires like the Michelin Pilot Sport 4S and Continental ExtremeContact Sport 02 show what the category does well: strong road manners, serious wet and dry grip, enough composure for occasional track use. They still trade tread life and cold-weather ability for it." },
      { type: "paragraph", text: "**Performance all-season.** A performance all-season is the rational one-set answer for a lot of daily drivers. Tires like the Michelin Pilot Sport All Season 4 and Continental ExtremeContact DWS06 Plus give you cold-weather flexibility, good wet performance, longer life, and more comfort than track-focused rubber." },
      { type: "paragraph", text: "The compromise is right there in the name." },
      { type: "paragraph", text: "They give up steering precision, peak warm-weather grip, and resistance to sustained track heat. An all-season can survive a novice track day at a sensible pace, but building a track car and expecting ordinary all-seasons to take repeated hot laps is asking the wrong tire to do the job." },
      { type: "paragraph", text: "**All-weather.** \"All-weather\" usually means an all-season tire carrying the three-peak mountain snowflake symbol (3PMSF). It makes sense for drivers who see regular snow but don't want to store and swap two sets." },
      { type: "paragraph", text: "The symbol is useful, but people give it more authority than it has. It certifies a minimum straight-line acceleration result on medium-packed snow. It doesn't test snow braking, cornering, or ice grip. A Michelin CrossClimate2 or Pirelli WeatherActive can be a strong year-round compromise, but no category label guarantees dedicated-winter performance." },
      { type: "paragraph", text: "Independent testing consistently shows the pattern: a dedicated summer tire stays strongest in warm dry and wet conditions, a dedicated winter tire leads in snow, and the best all-weather tires land between them — which is exactly where a compromise should land." },

      { type: "heading", text: "Track Tires: \"200TW\" Is Only the Beginning" },
      { type: "paragraph", text: "A 200-treadwear rating doesn't tell you how fast, durable, rain-capable, or heat-resistant a tire will be." },
      { type: "paragraph", text: "The UTQG treadwear number is a comparative wear grade produced under controlled conditions. Manufacturers assign the ratings themselves, and comparisons get less reliable across brands. Two tires stamped 200TW can have completely different personalities." },
      { type: "paragraph", text: "Enthusiasts split them into two useful groups." },
      { type: "paragraph", text: "**Super 200.** Tires like the Bridgestone Potenza RE-71RS and Yokohama A052 prioritize rapid warmup and peak pace. They're popular in autocross and time-attack, where one fast lap matters. That pace can come with quicker wear, more noise, and less consistency through a long session, and wet performance depends heavily on the specific model and remaining tread depth." },
      { type: "paragraph", text: "**Endurance 200.** The Hankook RS4 and Continental ExtremeContact Force take the other approach. They give up some ultimate pace but tolerate repeated laps and heat more consistently. For a dual-purpose track car, that consistency can matter more than winning one lap before the tire falls away." },
      { type: "paragraph", text: "**R-compound.** R-compound and DOT competition tires move further toward dedicated track duty: shallow tread, large blocks, stiff construction, compounds built to run in a specific heat range. They can be astonishing on a dry circuit. They can also be noisy, short-lived, cold-sensitive, and miserable around standing water. A DOT marking doesn't turn a competition tire into smart daily-driver rubber." },
      { type: "paragraph", text: "For frequent track use, a second wheel-and-tire set is usually the cleanest answer." },

      { type: "heading", text: "Dirt Tires: More Tread Isn't More Traction Everywhere" },
      { type: "paragraph", text: "**All-terrain.** For most vehicles that commute, travel, and explore trails, a modern all-terrain is the sensible starting point. A/T tires like the BFGoodrich All-Terrain T/A KO2 and Falken Wildpeak A/T3W balance pavement manners with traction on dirt, gravel, rock, sand, and moderate trails, and many now carry a 3PMSF rating." },
      { type: "paragraph", text: "They're still compromises. Against highway tires they usually bring more noise, weight, and rolling resistance, slower steering response, and no ability to clear deep mud like a true mud-terrain." },
      { type: "paragraph", text: "**Rugged-terrain or hybrid.** Hybrid tires sit somewhere between A/T and M/T — or at least that's the sales pitch. Models like the Nitto Ridge Grappler and Toyo Open Country R/T Trail run more open tread and aggressive shoulders than a conventional A/T while trying to keep acceptable highway manners. The category is loosely defined: aggressive appearance is about the only consistent trait, while off-road, wet, winter, and noise performance vary a lot model to model. Buy the test results, not the category name." },
      { type: "paragraph", text: "**Mud-terrain.** Mud-terrain tires earn their keep in deep mud and loose soil. Large voids let the tread sling material instead of packing solid, and aggressive shoulders bite in ruts and around obstacles. If that's your regular weekend, the road compromises may be worth it." },
      { type: "paragraph", text: "If your truck never leaves pavement, an M/T just gives you extra noise, weight, rolling resistance, tread squirm, and often weaker wet or packed-snow behavior in exchange for a look. That's an expensive costume. Modern M/Ts can be surprisingly civilized and owners disagree about how much noise is tolerable, but they're still the most specialized street-legal category on this side of the discussion." },
      { type: "paragraph", text: "**Dedicated off-road.** Sticky rock tires, bias-ply competition tires, and a lot of UTV and ATV tires go past ordinary M/T construction and can be exceptional on the surface they were built for. They're second-set or trailered tools. An NHS stamp means Not for Highway Service." },

      { type: "heading", text: "The Pavement Tax Nobody Photographs" },
      { type: "paragraph", text: "Aggressive tires charge rent every day." },
      { type: "paragraph", text: "Open tread makes more noise. Heavy tread and reinforced construction add rotating and unsprung mass, which takes more energy to accelerate and more work from the brakes and suspension. Steering can slow, ride quality can drop, and fuel economy can fall." },
      { type: "paragraph", text: "There's no honest universal \"big tires cost exactly this much mpg\" formula. Diameter, width, compound, pressure, gearing, wheel weight, aerodynamics, even speedometer error all muddy owner reports." },
      { type: "paragraph", text: "Controlled testing still shows the direction clearly: swap a highway tire for an all-terrain in the same size and you generally give up a little fuel economy, some wet braking, and some steering response for the extra capability. It's rarely free." },

      { type: "heading", text: "Load Range Isn't a Toughness Score" },
      { type: "paragraph", text: "Overland builds add bumpers, armor, drawers, tools, water, camping gear, sometimes a trailer. That load matters more than the badge on the hood." },
      { type: "paragraph", text: "The tire's load index has to support the vehicle at its heaviest realistic condition. Check the door placard, use the manufacturer's load-and-inflation tables, and weigh a heavily modified rig by axle if you need to." },
      { type: "paragraph", text: "\"Ten-ply rated\" doesn't necessarily mean ten physical plies. Load range describes load and inflation capability; actual sidewall construction varies by model and size." },
      { type: "paragraph", text: "An E-range tire may give a heavy build the capacity and durability it needs. On a light Jeep, it may just add weight, stiffness, and resistance to the trail flex you actually want. Owners have valid experiences on both sides — their vehicles, terrain, pressures, and tire constructions differ." },

      { type: "heading", text: "Airing Down Changes the Tire" },
      { type: "paragraph", text: "Lowering pressure off-road enlarges and reshapes the footprint, improves flotation, softens impacts, and lets the casing wrap around rocks and uneven ground. It's one of the most effective trail adjustments there is." },
      { type: "paragraph", text: "It also has no universal number. Vehicle and axle weight, tire construction, wheel width, bead retention, speed, and terrain all decide how low is useful. The internet's favorite 15-psi answer could be conservative for one rig and bead-losing territory for another." },
      { type: "paragraph", text: "Drop pressure gradually, watch the sidewall, keep to trail speeds, carry an accurate gauge and a compressor, and air back up before you hit pavement." },

      { type: "heading", text: "Stop Buying for the Flex Photo" },
      { type: "paragraph", text: "The common mistakes are easy to name." },
      { type: "paragraph", text: "Mud-terrains on a truck that never leaves the highway. Generic all-seasons on a car running sustained track sessions. R-compounds on a daily that regularly sees cold rain. E-range tires picked because the letter sounds tougher. A loaded overland build that never had its load index checked. Oversized tires bought without weighing the cost in weight, gearing, braking, clearance, and replacement price." },
      { type: "paragraph", text: "A tire can look perfect and still make the vehicle worse at nearly everything it actually does." },

      { type: "heading", text: "The Takeaway" },
      { type: "paragraph", text: "There's no universal best tire. There's only the best compromise for a specific vehicle, driver, climate, load, and use." },
      { type: "paragraph", text: "Write down where your next 10,000 miles will really happen. Which tire would that list tell you to buy — and which tire are you considering mostly because it'd look better in the parking-lot photo?" },
    ],
  },
  {
    slug: "why-community-rides-matter",
    title: "The Build Is Only Half of It: Why Community Rides Matter",
    seoTitle: "Why the Car Community Matters Beyond the Build",
    excerpt:
      "The build gets you through the gate. The people who teach, wrench, spot, recover, and make room for newcomers turn a collection of vehicles into a community — from the parking lot to the trailhead.",
    metaDescription:
      "From cars and coffee to trail rides, a good car community shares real knowledge, makes group travel safer, and helps when builds break.",
    category: "Culture",
    date: "2026-08-13",
    image: {
      src: "/img/blog/why-community-rides-matter.jpg",
      alt: "The Build Is Only Half Of It — a crew helping with a broken-down street car while another crew airs down tires on an off-road rig at a mountain pullout",
    },
    editorsPick: true,
    body: [
      { type: "paragraph", text: "Your build can be perfect and still leave you standing alone in a parking lot." },
      { type: "paragraph", text: "The car community is what happens after the hood goes up: somebody hears the miss, spots the loose bolt, hands you the right wrench, or tells you the line you are about to take is a terrible idea. The vehicle starts the conversation. The people give the hobby a pulse." },
      { type: "paragraph", text: "That is why organized cruises, cars and coffee, autocross weekends, trail runs, and overland convoys still matter. At their best, they turn private obsession into shared experience." },
      { type: "paragraph", text: "At their worst? They are traffic with matching stickers." },

      { type: "heading", text: "What the Car Community Teaches That the Internet Cannot" },
      { type: "paragraph", text: "Forums and videos are useful. We have all been saved by an ancient thread written by someone with a broken Photobucket link and the exact same problem." },
      { type: "paragraph", text: "But a screen cannot listen to your engine, feel the play in a wheel bearing, or watch what your suspension does under load. At a good street meet, autocross, or track day, you can see how a modification actually fits, sounds, wears, and survives. You can ask the owner what failed, what they would buy again, and what they regret." },
      { type: "paragraph", text: "The same thing happens on dirt. A trail guide can show you why one tire placement works, when momentum becomes wheelspin, how low pressure changes the vehicle, and when the smart move is the bypass. Watching a careful recovery in person teaches more than a stack of clips showing somebody yanking a truck by the wrong attachment point." },
      { type: "paragraph", text: "That knowledge is not automatic. You still have to ask questions, listen, and occasionally accept that the experienced person pointing at your sketchy setup may have a point." },

      { type: "heading", text: "Your Backup Plan Has a Name" },
      { type: "paragraph", text: "Things break. Street cars overheat in cruise traffic. Old wiring gives up at the gas stop. A trail tire loses a bead. A tie rod decides it has contributed enough to the project." },
      { type: "paragraph", text: "A solid group changes what happens next. Someone has a scan tool, jack, spare relay, tire plug kit, recovery strap, or the phone number of the person who knows that platform. More valuable, they have enough experience to stop the group from turning a small problem into a larger one." },
      { type: "paragraph", text: "That safety net does not excuse showing up unprepared. Good events check the basics and communicate expectations. SCCA RoadRally guidance calls for a street-legal, insured car with working safety equipment. One current Jeep Jamboree participant guide requires items such as proper tow points, a full-size spare, seat belts, and a GMRS radio." },
      { type: "paragraph", text: "A Sunday cruise does not need an inspection lane, and every trail day does not need a rulebook. \"We will figure it out\" works much better when the group planned before something went wrong." },

      { type: "heading", text: "Good Groups Make Room for Rookies" },
      { type: "paragraph", text: "Every expert was once the person quietly wondering where tech inspection was, how to use a radio, or whether a stock vehicle belonged there." },
      { type: "paragraph", text: "Good groups remember that." },
      { type: "paragraph", text: "SCCA's novice guidance recommends clear instructions, pre-event questions, experienced contacts, and deliberate interaction between newcomers and regulars. That is not hand-holding. It is how a car community survives longer than one generation." },
      { type: "paragraph", text: "On the street side, that can mean welcoming the daily driver, unfinished project, or spectator who came to learn. At an autocross or track event, it means explaining the process and keeping speed inside the controlled venue." },
      { type: "paragraph", text: "On an off-road trail ride, it means publishing honest difficulty, creating a beginner group, pointing out bypasses, and never shaming someone for asking for a spotter or deciding an obstacle is beyond their limit." },
      { type: "paragraph", text: "There is a difference between standards and gatekeeping. Requiring working brakes or safe recovery points protects everyone. Acting like somebody needs a certain badge, tire size, budget, age, or résumé before they can belong protects nothing except a fragile pecking order." },

      { type: "heading", text: "Yes, Cars and Coffee Can Be Awful" },
      { type: "paragraph", text: "The complaints are real. Some meets feel like the same expensive cars in the same reserved row while everyone else records content for people who are not there. Some cruises attract drivers who think a public road becomes a qualifying session because a pack is behind them." },
      { type: "paragraph", text: "Trail groups have their own version: the leader who hides the real difficulty, the built rig that disappears ahead, the person who blocks an obstacle for photos, or the driver who digs a new bypass rather than backing down." },
      { type: "paragraph", text: "Sometimes the event is the problem." },
      { type: "paragraph", text: "Owner discussions across r/cars and overlanding groups show both sides. People describe cliques, ego, reckless exits, endless waiting, and club politics. They also describe meeting mentors, finding track events, learning repairs, getting recovered, and making friends they would never have met otherwise." },
      { type: "paragraph", text: "Do not confuse a bad room with a dead hobby. Leave the group that rewards bad behavior and support the one that does the work." },

      { type: "heading", text: "Group Car Rides Need Structure" },
      { type: "paragraph", text: "A well-run cruise is not a rolling roadblock. It has a route, a briefing, lead and sweep cars, sensible spacing, regroup points, and a clear instruction to obey every traffic signal. PCA's touring standards state that safety matters more than staying together. Getting separated is inconvenient; running a red light to catch the group is dangerous." },
      { type: "paragraph", text: "Off-road trail rides need the same discipline in different clothes. Establish a radio channel. Keep the vehicle behind you in sight. Wait at junctions. Put one vehicle on an obstacle at a time. Match the pace to the least experienced driver, and split the convoy when size starts working against communication or trail access." },
      { type: "paragraph", text: "Experienced owners disagree about the ideal group size. Some prefer three to five vehicles. Others have run much larger groups successfully. There is no magic number. A five-rig mess is still a mess, while a larger ride with capable leaders, intermediate helpers, and a reliable sweep can work." },
      { type: "paragraph", text: "Structure is what keeps one person's mistake from becoming everybody's afternoon." },

      { type: "heading", text: "The Venue Remembers Who Showed Up" },
      { type: "paragraph", text: "Community includes the place hosting it." },
      { type: "paragraph", text: "A parking-lot meet survives because attendees respect the property owner, leave fire lanes open, control noise, clean up, and do not turn the exit into a burnout contest. One reckless departure can wipe out a pile of organizer work." },
      { type: "paragraph", text: "The dirt version has higher stakes. On National Forest System land, Motor Vehicle Use Maps identify which routes are legal for which vehicle classes and seasons. Tire tracks are not permission. Tread Lightly's guidance is equally plain: stay on designated routes, drive over rather than around obstacles, yield to other users, and keep speed and noise down." },
      { type: "paragraph", text: "A club cleanup is worthwhile. It does not buy permission to cut a new line the next weekend." },
      { type: "paragraph", text: "The best groups understand that access is borrowed. Showing up means protecting the road, lot, track, or trail so the next gathering can happen." },

      { type: "heading", text: "The People Are the Other Half" },
      { type: "paragraph", text: "The car gets you through the gate. The people teach you where to stand, what to watch, which mistake they already paid for, and when to put the tools down and order food." },
      { type: "paragraph", text: "No group is perfect. Some are too big. Some are too cliquey. Some need better rules, better leaders, or a firm goodbye for the person who keeps making everyone look bad. The value comes from people making the hobby safer, smarter, more welcoming, and more fun." },
      { type: "paragraph", text: "The build is half of it. The people willing to teach, spot, wrench, recover, wait, and share the road or trail are the other half." },
      { type: "paragraph", text: "Who was the first person in the car community who helped you when they did not have to — and what were you driving when it happened?" },
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug && p.body);
}

export function getPublishedPosts(): BlogPost[] {
  return posts.filter((p) => p.body);
}

/** Every post, newest first — the full archive, not just a curated slice. */
export function getAllPostsSorted(): BlogPost[] {
  return [...posts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getEditorsPicks(): BlogPost[] {
  return posts.filter((p) => p.editorsPick);
}
